import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { supaInsert as supaIns } from "../lib/supabase";


const langs = [
  { code: "ar", name: "العربية", dir: "rtl" },
  { code: "en", name: "English", dir: "ltr" },
  { code: "tr", name: "Türkçe", dir: "ltr" },
  { code: "ur", name: "اردو", dir: "rtl" },
  { code: "ms", name: "Melayu", dir: "ltr" },
  { code: "fr", name: "Français", dir: "ltr" },
  { code: "fa", name: "فارسی", dir: "rtl" },
  { code: "bn", name: "বাংলা", dir: "ltr" },
  { code: "hi", name: "हिन्दी", dir: "ltr" },
];

const T = {
  ar:{bismillah:"بسم الله الرحمن الرحيم",site_name:"مشروع منافع",site_desc:"لدعوة الحجاج والمعتمرين",login:"تسجيل الدخول",hero_title:"منافع",hero_sub:"مشروع",n_home:"الرئيسية",n_vid:"الفيديوهات",n_quran:"القرآن الكريم",n_lib:"المكتبة",n_hajj:"الحج",n_umrah:"العمرة",n_contest:"المسابقة",s_vid:"فيديو تعليمي",s_book:"كتاب إسلامي",s_lang:"لغات مدعومة",s_visit:"زائر شهرياً",vid_tag:"فيديوهات مميزة",vid_title:"مكتبة الفيديوهات الإسلامية",vid_desc:"سلسلة متميزة من المحاضرات العلمية والدروس التعليمية",vid_all:"عرض جميع الفيديوهات",q_tag:"القرآن الكريم",q_title:"اقرأ واستمع للقرآن الكريم",q_desc:"قراءة وتلاوة وتفسير بأكثر من 9 لغات",q_browse:"تصفح القرآن الكريم",q_fatiha:"سورة الفاتحة",m_tag:"أدلة المناسك",hu_title:"الحج والعمرة",hu_desc:"دليل شامل خطوة بخطوة لأداء المناسك",h_guide:"دليل الحج",h_gdesc:"رحلة تفاعلية شاملة تأخذك خطوة بخطوة في مناسك الحج، من الإحرام حتى طواف الوداع",h_start:"ابدأ رحلة الحج",u_guide:"دليل العمرة",u_gdesc:"دليل تفاعلي ميسّر لأداء العمرة بالطريقة الصحيحة، مع الأدعية والنصائح العملية",u_start:"ابدأ رحلة العمرة",l_tag:"الكتب الإسلامية",l_title:"المكتبة الإسلامية",l_desc:"مجموعة مختارة من الكتب والرسائل في العلوم الشرعية",l_read:"قراءة الكتاب",l_all:"تصفح المكتبة كاملة",c_tag:"اختبر معلوماتك",c_title:"مسابقة منافع",c_desc:"شارك في المسابقة واربح جوائز قيمة — أسئلة متنوعة تتغير باستمرار",c_now:"شارك الآن",c_qlabel:"السؤال",f_title:"شاركنا رأيك",f_desc:"رأيك يهمنا لتحسين تجربتك",f_ph:"اكتب تعليقك هنا...",f_send:"إرسال التقييم",f_thx:"شكراً لك! تم إرسال تقييمك بنجاح",ft_links:"روابط سريعة",ft_langs:"اللغات المدعومة",ft_copy:"مشروع منافع — لدعوة الحجاج والمعتمرين. جميع الحقوق محفوظة",ft_about:"منصة إسلامية رقمية تهدف لنفع الحجاج والمعتمرين وعامة المسلمين حول العالم"},
  en:{bismillah:"In the Name of Allah, the Most Gracious, the Most Merciful",site_name:"Manafea Project",site_desc:"For Hajj & Umrah Dawah",login:"Login",hero_title:"Manafea",hero_sub:"Project",n_home:"Home",n_vid:"Videos",n_quran:"Holy Quran",n_lib:"Library",n_hajj:"Hajj",n_umrah:"Umrah",n_contest:"Contest",s_vid:"Educational Videos",s_book:"Islamic Books",s_lang:"Supported Languages",s_visit:"Monthly Visitors",vid_tag:"Featured Videos",vid_title:"Islamic Video Library",vid_desc:"A distinguished series of scientific lectures and educational lessons",vid_all:"View All Videos",q_tag:"Holy Quran",q_title:"Read & Listen to the Holy Quran",q_desc:"Reading, recitation and interpretation in 9+ languages",q_browse:"Browse the Holy Quran",q_fatiha:"Surah Al-Fatiha",m_tag:"Rituals Guides",hu_title:"Hajj & Umrah",hu_desc:"A comprehensive step-by-step guide to performing the rituals",h_guide:"Hajj Guide",h_gdesc:"A comprehensive interactive journey taking you step by step through Hajj rituals",h_start:"Start Hajj Journey",u_guide:"Umrah Guide",u_gdesc:"An easy interactive guide to performing Umrah correctly with duas and practical tips",u_start:"Start Umrah Journey",l_tag:"Islamic Books",l_title:"Islamic Library",l_desc:"A curated collection of books and treatises in Islamic sciences",l_read:"Read Book",l_all:"Browse Full Library",c_tag:"Test Your Knowledge",c_title:"Manafea Contest",c_desc:"Participate and win valuable prizes — diverse questions that change constantly",c_now:"Participate Now",c_qlabel:"Question",f_title:"Share Your Feedback",f_desc:"Your feedback helps us improve your experience",f_ph:"Write your comment here...",f_send:"Submit Rating",f_thx:"Thank you! Your feedback has been submitted successfully",ft_links:"Quick Links",ft_langs:"Supported Languages",ft_copy:"Manafea Project — For Hajj & Umrah Dawah. All Rights Reserved",ft_about:"A digital Islamic platform aiming to benefit pilgrims and Muslims around the world"},
  tr:{bismillah:"Rahman ve Rahim olan Allah'ın adıyla",site_name:"Menafi Projesi",site_desc:"Hacılar ve Umreciler İçin",login:"Giriş",hero_title:"Menafi",hero_sub:"Proje",n_home:"Ana Sayfa",n_vid:"Videolar",n_quran:"Kur'an-ı Kerim",n_lib:"Kütüphane",n_hajj:"Hac",n_umrah:"Umre",n_contest:"Yarışma",s_vid:"Eğitim Videosu",s_book:"İslami Kitap",s_lang:"Desteklenen Dil",s_visit:"Aylık Ziyaretçi",vid_tag:"Öne Çıkan Videolar",vid_title:"İslami Video Kütüphanesi",vid_desc:"Seçkin ilmi dersler ve eğitim serisi",vid_all:"Tüm Videoları Görüntüle",q_tag:"Kur'an-ı Kerim",q_title:"Kur'an-ı Kerim'i Okuyun ve Dinleyin",q_desc:"9+ dilde okuma, tilavet ve tefsir",q_browse:"Kur'an-ı Kerim'i İnceleyin",q_fatiha:"Fatiha Suresi",m_tag:"İbadet Rehberleri",hu_title:"Hac ve Umre",hu_desc:"İbadetleri adım adım gerçekleştirme rehberi",h_guide:"Hac Rehberi",h_gdesc:"Hac ibadetlerinde adım adım rehberlik eden kapsamlı etkileşimli bir yolculuk",h_start:"Hac Yolculuğuna Başla",u_guide:"Umre Rehberi",u_gdesc:"Dualar ve pratik ipuçlarıyla Umre'yi doğru yapma rehberi",u_start:"Umre Yolculuğuna Başla",l_tag:"İslami Kitaplar",l_title:"İslami Kütüphane",l_desc:"İslami ilimlerde seçme kitap ve risaleler koleksiyonu",l_read:"Kitabı Oku",l_all:"Tüm Kütüphaneyi İncele",c_tag:"Bilgini Test Et",c_title:"Menafi Yarışması",c_desc:"Yarışmaya katılın ve değerli ödüller kazanın",c_now:"Şimdi Katıl",c_qlabel:"Soru",f_title:"Görüşünüzü Paylaşın",f_desc:"Görüşünüz deneyiminizi geliştirmemize yardımcı olur",f_ph:"Yorumunuzu buraya yazın...",f_send:"Değerlendirmeyi Gönder",f_thx:"Teşekkürler! Değerlendirmeniz başarıyla gönderildi",ft_links:"Hızlı Bağlantılar",ft_langs:"Desteklenen Diller",ft_copy:"Menafi Projesi — Tüm Hakları Saklıdır",ft_about:"Hacılar ve dünya genelindeki Müslümanlara fayda sağlamayı amaçlayan dijital İslami platform"},
  ur:{bismillah:"اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے",site_name:"منافع پروجیکٹ",site_desc:"حاجیوں اور عمرہ کرنے والوں کی دعوت",login:"لاگ ان",hero_title:"منافع",hero_sub:"پروجیکٹ",n_home:"ہوم",n_vid:"ویڈیوز",n_quran:"قرآن کریم",n_lib:"لائبریری",n_hajj:"حج",n_umrah:"عمرہ",n_contest:"مقابلہ",s_vid:"تعلیمی ویڈیوز",s_book:"اسلامی کتابیں",s_lang:"معاون زبانیں",s_visit:"ماہانہ زائرین",vid_tag:"نمایاں ویڈیوز",vid_title:"اسلامی ویڈیو لائبریری",vid_desc:"علمی محاضرات اور تعلیمی اسباق کا ایک ممتاز سلسلہ",vid_all:"تمام ویڈیوز دیکھیں",q_tag:"قرآن کریم",q_title:"قرآن کریم پڑھیں اور سنیں",q_desc:"9+ زبانوں میں قراءت، تلاوت اور تفسیر",q_browse:"قرآن کریم براؤز کریں",q_fatiha:"سورۃ الفاتحہ",m_tag:"مناسک گائیڈ",hu_title:"حج اور عمرہ",hu_desc:"مناسک ادا کرنے کی مکمل مرحلہ وار گائیڈ",h_guide:"حج گائیڈ",h_gdesc:"حج کے مناسک میں قدم بہ قدم رہنمائی کرنے والا ایک جامع سفر",h_start:"حج کا سفر شروع کریں",u_guide:"عمرہ گائیڈ",u_gdesc:"دعاؤں اور عملی نصائح کے ساتھ عمرہ صحیح طریقے سے ادا کرنے کی گائیڈ",u_start:"عمرہ کا سفر شروع کریں",l_tag:"اسلامی کتابیں",l_title:"اسلامی لائبریری",l_desc:"اسلامی علوم میں منتخب کتابوں اور رسائل کا مجموعہ",l_read:"کتاب پڑھیں",l_all:"پوری لائبریری دیکھیں",c_tag:"اپنی معلومات جانچیں",c_title:"منافع مقابلہ",c_desc:"مقابلے میں حصہ لیں اور قیمتی انعامات جیتیں",c_now:"ابھی شرکت کریں",c_qlabel:"سوال",f_title:"اپنی رائے دیں",f_desc:"آپ کی رائے ہمیں آپ کا تجربہ بہتر بنانے میں مدد کرتی ہے",f_ph:"اپنا تبصرہ یہاں لکھیں...",f_send:"ریٹنگ جمع کریں",f_thx:"شکریہ! آپ کی رائے کامیابی سے جمع ہو گئی",ft_links:"فوری لنکس",ft_langs:"معاون زبانیں",ft_copy:"منافع پروجیکٹ — جملہ حقوق محفوظ ہیں",ft_about:"ایک ڈیجیٹل اسلامی پلیٹ فارم جو حاجیوں اور دنیا بھر کے مسلمانوں کو فائدہ پہنچانے کا مقصد رکھتا ہے"},
  ms:{bismillah:"Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang",site_name:"Projek Manafea",site_desc:"Untuk Dakwah Haji & Umrah",login:"Log Masuk",hero_title:"Manafea",hero_sub:"Projek",n_home:"Utama",n_vid:"Video",n_quran:"Al-Quran",n_lib:"Perpustakaan",n_hajj:"Haji",n_umrah:"Umrah",n_contest:"Pertandingan",s_vid:"Video Pendidikan",s_book:"Buku Islam",s_lang:"Bahasa Disokong",s_visit:"Pelawat Bulanan",vid_tag:"Video Pilihan",vid_title:"Perpustakaan Video Islam",vid_desc:"Siri kuliah ilmiah dan pelajaran pendidikan yang terpilih",vid_all:"Lihat Semua Video",q_tag:"Al-Quran",q_title:"Baca & Dengar Al-Quran",q_desc:"Bacaan, tilawah dan tafsir dalam 9+ bahasa",q_browse:"Layari Al-Quran",q_fatiha:"Surah Al-Fatihah",m_tag:"Panduan Manasik",hu_title:"Haji & Umrah",hu_desc:"Panduan langkah demi langkah untuk menunaikan manasik",h_guide:"Panduan Haji",h_gdesc:"Perjalanan interaktif komprehensif membimbing anda langkah demi langkah",h_start:"Mulakan Perjalanan Haji",u_guide:"Panduan Umrah",u_gdesc:"Panduan interaktif mudah untuk menunaikan Umrah dengan betul",u_start:"Mulakan Perjalanan Umrah",l_tag:"Buku-buku Islam",l_title:"Perpustakaan Islam",l_desc:"Koleksi buku dan risalah terpilih dalam ilmu Islam",l_read:"Baca Buku",l_all:"Layari Perpustakaan Penuh",c_tag:"Uji Pengetahuan Anda",c_title:"Pertandingan Manafea",c_desc:"Sertai pertandingan dan menangi hadiah berharga",c_now:"Sertai Sekarang",c_qlabel:"Soalan",f_title:"Kongsi Maklum Balas",f_desc:"Maklum balas anda membantu kami meningkatkan pengalaman anda",f_ph:"Tulis ulasan anda di sini...",f_send:"Hantar Penilaian",f_thx:"Terima kasih! Maklum balas anda telah berjaya dihantar",ft_links:"Pautan Pantas",ft_langs:"Bahasa Disokong",ft_copy:"Projek Manafea — Hak Cipta Terpelihara",ft_about:"Platform Islam digital yang bertujuan memberi manfaat kepada jemaah haji dan umat Islam di seluruh dunia"},
  fr:{bismillah:"Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux",site_name:"Projet Manafea",site_desc:"Pour la Dawah du Hajj et de la Omra",login:"Connexion",hero_title:"Manafea",hero_sub:"Projet",n_home:"Accueil",n_vid:"Vidéos",n_quran:"Le Saint Coran",n_lib:"Bibliothèque",n_hajj:"Hajj",n_umrah:"Omra",n_contest:"Concours",s_vid:"Vidéos Éducatives",s_book:"Livres Islamiques",s_lang:"Langues Supportées",s_visit:"Visiteurs Mensuels",vid_tag:"Vidéos en Vedette",vid_title:"Bibliothèque Vidéo Islamique",vid_desc:"Une série de conférences et de cours éducatifs",vid_all:"Voir Toutes les Vidéos",q_tag:"Le Saint Coran",q_title:"Lisez et Écoutez le Saint Coran",q_desc:"Lecture, récitation et interprétation en 9+ langues",q_browse:"Parcourir le Saint Coran",q_fatiha:"Sourate Al-Fatiha",m_tag:"Guides des Rituels",hu_title:"Hajj & Omra",hu_desc:"Un guide complet étape par étape pour accomplir les rituels",h_guide:"Guide du Hajj",h_gdesc:"Un voyage interactif complet vous guidant étape par étape",h_start:"Commencer le Hajj",u_guide:"Guide de la Omra",u_gdesc:"Un guide interactif pour accomplir la Omra correctement",u_start:"Commencer la Omra",l_tag:"Livres Islamiques",l_title:"Bibliothèque Islamique",l_desc:"Une collection de livres et traités en sciences islamiques",l_read:"Lire le Livre",l_all:"Parcourir la Bibliothèque",c_tag:"Testez vos Connaissances",c_title:"Concours Manafea",c_desc:"Participez au concours et gagnez des prix",c_now:"Participer Maintenant",c_qlabel:"Question",f_title:"Partagez votre Avis",f_desc:"Votre avis nous aide à améliorer votre expérience",f_ph:"Écrivez votre commentaire ici...",f_send:"Envoyer l'Évaluation",f_thx:"Merci! Votre avis a été envoyé avec succès",ft_links:"Liens Rapides",ft_langs:"Langues Supportées",ft_copy:"Projet Manafea — Tous Droits Réservés",ft_about:"Une plateforme islamique numérique visant à bénéficier les pèlerins et les musulmans du monde entier"},
  fa:{bismillah:"به نام خداوند بخشنده مهربان",site_name:"پروژه منافع",site_desc:"برای دعوت حاجیان و معتمرین",login:"ورود",hero_title:"منافع",hero_sub:"پروژه",n_home:"خانه",n_vid:"ویدیوها",n_quran:"قرآن کریم",n_lib:"کتابخانه",n_hajj:"حج",n_umrah:"عمره",n_contest:"مسابقه",s_vid:"ویدیوی آموزشی",s_book:"کتاب اسلامی",s_lang:"زبان پشتیبانی",s_visit:"بازدید ماهانه",vid_tag:"ویدیوهای ویژه",vid_title:"کتابخانه ویدیوی اسلامی",vid_desc:"مجموعه‌ای از سخنرانی‌های علمی و درس‌های آموزشی",vid_all:"مشاهده همه ویدیوها",q_tag:"قرآن کریم",q_title:"قرآن کریم بخوانید و بشنوید",q_desc:"قرائت، تلاوت و تفسیر در بیش از 9 زبان",q_browse:"مرور قرآن کریم",q_fatiha:"سوره فاتحه",m_tag:"راهنمای مناسک",hu_title:"حج و عمره",hu_desc:"راهنمای جامع مرحله به مرحله انجام مناسک",h_guide:"راهنمای حج",h_gdesc:"سفری تعاملی جامع که شما را گام به گام در مناسک حج راهنمایی می‌کند",h_start:"شروع سفر حج",u_guide:"راهنمای عمره",u_gdesc:"راهنمای تعاملی آسان برای انجام صحیح عمره",u_start:"شروع سفر عمره",l_tag:"کتاب‌های اسلامی",l_title:"کتابخانه اسلامی",l_desc:"مجموعه‌ای منتخب از کتاب‌ها و رساله‌ها در علوم اسلامی",l_read:"خواندن کتاب",l_all:"مرور کتابخانه کامل",c_tag:"دانش خود را آزمایید",c_title:"مسابقه منافع",c_desc:"در مسابقه شرکت کنید و جوایز ارزشمند ببرید",c_now:"اکنون شرکت کنید",c_qlabel:"سؤال",f_title:"نظر خود را بیان کنید",f_desc:"نظر شما به ما در بهبود تجربه شما کمک می‌کند",f_ph:"نظر خود را اینجا بنویسید...",f_send:"ارسال امتیاز",f_thx:"با تشکر! نظر شما با موفقیت ارسال شد",ft_links:"لینک‌های سریع",ft_langs:"زبان‌های پشتیبانی شده",ft_copy:"پروژه منافع — تمامی حقوق محفوظ است",ft_about:"پلتفرم دیجیتال اسلامی با هدف بهره‌مندی حاجیان و مسلمانان سراسر جهان"},
  bn:{bismillah:"পরম করুণাময় অসীম দয়ালু আল্লাহর নামে",site_name:"মানাফেয়া প্রকল্প",site_desc:"হজ্জ ও উমরাহ দাওয়াহর জন্য",login:"লগইন",hero_title:"মানাফেয়া",hero_sub:"প্রকল্প",n_home:"হোম",n_vid:"ভিডিও",n_quran:"পবিত্র কুরআন",n_lib:"লাইব্রেরি",n_hajj:"হজ্জ",n_umrah:"উমরাহ",n_contest:"প্রতিযোগিতা",s_vid:"শিক্ষামূলক ভিডিও",s_book:"ইসলামিক বই",s_lang:"সমর্থিত ভাষা",s_visit:"মাসিক দর্শক",vid_tag:"বৈশিষ্ট্যযুক্ত ভিডিও",vid_title:"ইসলামিক ভিডিও লাইব্রেরি",vid_desc:"বৈজ্ঞানিক বক্তৃতা এবং শিক্ষামূলক পাঠের একটি বিশিষ্ট সিরিজ",vid_all:"সব ভিডিও দেখুন",q_tag:"পবিত্র কুরআন",q_title:"পবিত্র কুরআন পড়ুন ও শুনুন",q_desc:"9+ ভাষায় পাঠ, তিলাওয়াত এবং তাফসীর",q_browse:"পবিত্র কুরআন ব্রাউজ করুন",q_fatiha:"সূরা আল-ফাতিহা",m_tag:"মানাসিক গাইড",hu_title:"হজ্জ ও উমরাহ",hu_desc:"মানাসিক পালনের জন্য একটি বিস্তৃত ধাপে ধাপে গাইড",h_guide:"হজ্জ গাইড",h_gdesc:"হজ্জের মানাসিকে ধাপে ধাপে গাইড করার একটি ব্যাপক যাত্রা",h_start:"হজ্জ যাত্রা শুরু করুন",u_guide:"উমরাহ গাইড",u_gdesc:"দোয়া ও ব্যবহারিক টিপস সহ সঠিকভাবে উমরাহ পালনের গাইড",u_start:"উমরাহ যাত্রা শুরু করুন",l_tag:"ইসলামিক বই",l_title:"ইসলামিক লাইব্রেরি",l_desc:"ইসলামি বিজ্ঞানে বই ও গ্রন্থের একটি নির্বাচিত সংগ্রহ",l_read:"বই পড়ুন",l_all:"সম্পূর্ণ লাইব্রেরি ব্রাউজ করুন",c_tag:"আপনার জ্ঞান পরীক্ষা করুন",c_title:"মানাফেয়া প্রতিযোগিতা",c_desc:"প্রতিযোগিতায় অংশ নিন এবং মূল্যবান পুরস্কার জিতুন",c_now:"এখনই অংশ নিন",c_qlabel:"প্রশ্ন",f_title:"আপনার মতামত জানান",f_desc:"আপনার মতামত আমাদের আপনার অভিজ্ঞতা উন্নত করতে সাহায্য করে",f_ph:"আপনার মন্তব্য এখানে লিখুন...",f_send:"রেটিং জমা দিন",f_thx:"ধন্যবাদ! আপনার মতামত সফলভাবে জমা হয়েছে",ft_links:"দ্রুত লিঙ্ক",ft_langs:"সমর্থিত ভাষাসমূহ",ft_copy:"মানাফেয়া প্রকল্প — সর্বস্বত্ব সংরক্ষিত",ft_about:"হজযাত্রী এবং বিশ্বজুড়ে মুসলমানদের উপকারের লক্ষ্যে একটি ডিজিটাল ইসলামিক প্ল্যাটফর্ম"},
  hi:{bismillah:"अल्लाह के नाम से जो बड़ा कृपाशील अत्यंत दयावान है",site_name:"मनाफ़ेआ प्रोजेक्ट",site_desc:"हज और उमरा दावत के लिए",login:"लॉगिन",hero_title:"मनाफ़ेआ",hero_sub:"प्रोजेक्ट",n_home:"होम",n_vid:"वीडियो",n_quran:"पवित्र कुरान",n_lib:"पुस्तकालय",n_hajj:"हज",n_umrah:"उमरा",n_contest:"प्रतियोगिता",s_vid:"शैक्षिक वीडियो",s_book:"इस्लामी किताबें",s_lang:"समर्थित भाषाएं",s_visit:"मासिक आगंतुक",vid_tag:"विशेष वीडियो",vid_title:"इस्लामी वीडियो पुस्तकालय",vid_desc:"वैज्ञानिक व्याख्यान और शैक्षिक पाठों की एक विशिष्ट श्रृंखला",vid_all:"सभी वीडियो देखें",q_tag:"पवित्र कुरान",q_title:"पवित्र कुरान पढ़ें और सुनें",q_desc:"9+ भाषाओं में पठन, तिलावत और तफ़सीर",q_browse:"पवित्र कुरान ब्राउज़ करें",q_fatiha:"सूरह अल-फ़ातिहा",m_tag:"मनासिक गाइड",hu_title:"हज और उमरा",hu_desc:"मनासिक के प्रदर्शन के लिए एक व्यापक चरण-दर-चरण गाइड",h_guide:"हज गाइड",h_gdesc:"हज के मनासिक में कदम दर कदम मार्गदर्शन करने वाली यात्रा",h_start:"हज यात्रा शुरू करें",u_guide:"उमरा गाइड",u_gdesc:"दुआओं और व्यावहारिक सुझावों के साथ उमरा सही तरीके से करने की गाइड",u_start:"उमरा यात्रा शुरू करें",l_tag:"इस्लामी किताबें",l_title:"इस्लामी पुस्तकालय",l_desc:"इस्लामी विज्ञान में पुस्तकों और ग्रंथों का एक चयनित संग्रह",l_read:"किताब पढ़ें",l_all:"पूरी लाइब्रेरी ब्राउज़ करें",c_tag:"अपना ज्ञान परखें",c_title:"मनाफ़ेआ प्रतियोगिता",c_desc:"प्रतियोगिता में भाग लें और कीमती पुरस्कार जीतें",c_now:"अभी भाग लें",c_qlabel:"प्रश्न",f_title:"अपनी राय साझा करें",f_desc:"आपकी राय हमें आपके अनुभव को बेहतर बनाने में मदद करती है",f_ph:"अपनी टिप्पणी यहाँ लिखें...",f_send:"रेटिंग सबमिट करें",f_thx:"धन्यवाद! आपकी प्रतिक्रिया सफलतापूर्वक भेजी गई",ft_links:"त्वरित लिंक",ft_langs:"समर्थित भाषाएं",ft_copy:"मनाफ़ेआ प्रोजेक्ट — सभी अधिकार सुरक्षित",ft_about:"तीर्थयात्रियों और दुनिया भर के मुसलमानों को लाभ पहुंचाने के उद्देश्य से एक डिजिटल इस्लामी मंच"},
};

const SL = {
  ar:[{a:"﴿ لِيَشْهَدُوا مَنَافِعَ لَهُمْ وَيَذْكُرُوا اسْمَ اللَّهِ فِي أَيَّامٍ مَعْلُومَاتٍ ﴾",s:"سورة الحج ٢٨"},{a:"﴿ وَلِلَّهِ عَلَى النَّاسِ حِجُّ الْبَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا ﴾",s:"آل عمران ٩٧"},{a:"﴿ وَأَتِمُّوا الْحَجَّ وَالْعُمْرَةَ لِلَّهِ ﴾",s:"البقرة ١٩٦"}],
  en:[{a:"That they may witness benefits for themselves and mention the name of Allah on known days",s:"Al-Hajj 28"},{a:"And to Allah from the people is a pilgrimage to the House for whoever is able",s:"Aal-e-Imran 97"},{a:"And complete the Hajj and Umrah for Allah",s:"Al-Baqarah 196"}],
  tr:[{a:"Kendilerine ait menfaatlere şahit olsunlar ve bilinen günlerde Allah'ın adını ansınlar",s:"Hac 28"},{a:"Yoluna gücü yetenlerin Beyt'i haccetmesi Allah'ın insanlar üzerindeki hakkıdır",s:"Âl-i İmran 97"},{a:"Haccı ve umreyi Allah için tamamlayın",s:"Bakara 196"}],
  ur:[{a:"﴿ تاکہ وہ اپنے فائدے دیکھیں اور مقررہ دنوں میں اللہ کا نام لیں ﴾",s:"الحج ٢٨"},{a:"﴿ اور اللہ کے لیے لوگوں پر بیت اللہ کا حج فرض ہے ﴾",s:"آل عمران ٩٧"},{a:"﴿ اور حج اور عمرہ اللہ کے لیے پورے کرو ﴾",s:"البقرۃ ١٩٦"}],
  ms:[{a:"Supaya mereka menyaksikan manfaat bagi mereka dan menyebut nama Allah pada hari-hari yang diketahui",s:"Al-Hajj 28"},{a:"Dan Allah mewajibkan manusia mengerjakan haji ke Baitullah bagi yang mampu",s:"Ali Imran 97"},{a:"Dan sempurnakanlah ibadah haji dan umrah kerana Allah",s:"Al-Baqarah 196"}],
  fr:[{a:"Pour témoigner des bienfaits et invoquer le nom d'Allah aux jours fixés",s:"Al-Hajj 28"},{a:"C'est un devoir envers Allah pour les gens qui ont les moyens d'aller en pèlerinage",s:"Al Imran 97"},{a:"Et accomplissez le Hajj et la Omra pour Allah",s:"Al-Baqarah 196"}],
  fa:[{a:"﴿ تا منافعی را برای خود شاهد باشند و نام خدا را در روزهای معلوم ببرند ﴾",s:"حج ٢٨"},{a:"﴿ و برای خدا بر مردم حج خانه واجب است ﴾",s:"آل عمران ٩٧"},{a:"﴿ و حج و عمره را برای خدا به تمام رسانید ﴾",s:"بقره ١٩٦"}],
  bn:[{a:"যাতে তারা তাদের কল্যাণ প্রত্যক্ষ করে এবং নির্দিষ্ট দিনগুলিতে আল্লাহর নাম স্মরণ করে",s:"আল-হাজ্জ ২৮"},{a:"মানুষের মধ্যে যারা সেখানে যাওয়ার সামর্থ্য রাখে তাদের উপর হজ্জ ফরজ",s:"আলে ইমরান ৯৭"},{a:"এবং আল্লাহর উদ্দেশ্যে হজ্জ ও উমরাহ পূর্ণ করো",s:"আল-বাকারাহ ১৯৬"}],
  hi:[{a:"ताकि वे अपने लाभ देखें और ज्ञात दिनों में अल्लाह का नाम लें",s:"अल-हज्ज 28"},{a:"और अल्लाह के लिए लोगों पर बैतुल्लाह का हज फ़र्ज़ है",s:"आले इमरान 97"},{a:"और हज और उमरा को अल्लाह के लिए पूरा करो",s:"अल-बक़रह 196"}],
};

const CQ = {
  ar:[{q:"ما هو أعظم أركان الحج؟",a:"الطواف",b:"السعي بين الصفا والمروة",c:"الوقوف بعرفة",x:"c"}],
  en:[{q:"What is the greatest pillar of Hajj?",a:"Tawaf",b:"Sai between Safa and Marwah",c:"Standing at Arafah",x:"c"}],
  tr:[{q:"Haccın en büyük rüknü nedir?",a:"Tavaf",b:"Safa ile Merve arası Say",c:"Arafat'ta vakfe",x:"c"}],
  ur:[{q:"حج کا سب سے بڑا رکن کیا ہے؟",a:"طواف",b:"صفا اور مروہ کے درمیان سعی",c:"عرفات میں وقوف",x:"c"}],
  ms:[{q:"Apakah rukun Haji yang paling besar?",a:"Tawaf",b:"Saie antara Safa dan Marwah",c:"Wukuf di Arafah",x:"c"}],
  fr:[{q:"Quel est le plus grand pilier du Hajj?",a:"Le Tawaf",b:"Le Sa'i entre Safa et Marwa",c:"La station à Arafat",x:"c"}],
  fa:[{q:"بزرگترین رکن حج چیست؟",a:"طواف",b:"سعی بین صفا و مروه",c:"وقوف در عرفات",x:"c"}],
  bn:[{q:"হজ্জের সবচেয়ে বড় রুকন কোনটি?",a:"তাওয়াফ",b:"সাফা ও মারওয়ার মধ্যে সাঈ",c:"আরাফাতে অবস্থান",x:"c"}],
  hi:[{q:"हज का सबसे बड़ा रुक्न क्या है?",a:"तवाफ",b:"सफा और मरवा के बीच सई",c:"अरफात में वक़ूफ़",x:"c"}],
};

const BK = {
  ar:[{t:"الدين الصحيح",a:"د. أبو أمينة فيلبس"},{t:"العقيدة الصحيحة",a:"ابن باز"},{t:"حصن المسلم",a:"سعيد القحطاني"},{t:"رياض الصالحين",a:"الإمام النووي"},{t:"الأصول الثلاثة",a:"محمد بن عبدالوهاب"}],
  en:[{t:"The True Religion",a:"Dr. Abu Ameenah Philips"},{t:"The Correct Creed",a:"Ibn Baz"},{t:"Fortress of the Muslim",a:"Said Al-Qahtani"},{t:"Gardens of the Righteous",a:"Imam An-Nawawi"},{t:"The Three Fundamentals",a:"M. ibn Abdul-Wahhab"}],
  tr:[{t:"Gerçek Din",a:"Dr. Ebu Emine Philips"},{t:"Doğru İnanç",a:"İbn Baz"},{t:"Müslümanın Kalesi",a:"Said el-Kahtani"},{t:"Salihler Bahçesi",a:"İmam Nevevi"},{t:"Üç Temel İlke",a:"Muhammed b. Abdülvehhab"}],
  ur:[{t:"سچا دین",a:"ڈاکٹر ابو امینہ فلپس"},{t:"صحیح عقیدہ",a:"ابن باز"},{t:"حصن المسلم",a:"سعید القحطانی"},{t:"ریاض الصالحین",a:"امام نووی"},{t:"تین اصول",a:"محمد بن عبدالوہاب"}],
  ms:[{t:"Agama Yang Benar",a:"Dr. Abu Ameenah Philips"},{t:"Akidah Yang Betul",a:"Ibn Baz"},{t:"Benteng Muslim",a:"Said Al-Qahtani"},{t:"Taman Orang Soleh",a:"Imam An-Nawawi"},{t:"Tiga Asas Utama",a:"Muhammad bin Abdul Wahhab"}],
  fr:[{t:"La Vraie Religion",a:"Dr. Abu Ameenah Philips"},{t:"Le Credo Correct",a:"Ibn Baz"},{t:"La Citadelle du Musulman",a:"Said Al-Qahtani"},{t:"Les Jardins des Vertueux",a:"Imam An-Nawawi"},{t:"Les Trois Fondements",a:"M. ibn Abdul-Wahhab"}],
  fa:[{t:"دین حقیقی",a:"دکتر ابوامینه فیلپس"},{t:"عقیده صحیح",a:"ابن باز"},{t:"حصن المسلم",a:"سعید القحطانی"},{t:"ریاض الصالحین",a:"امام نووی"},{t:"سه اصل",a:"محمد بن عبدالوهاب"}],
  bn:[{t:"সত্য ধর্ম",a:"ড. আবু আমিনাহ ফিলিপস"},{t:"সঠিক আকীদা",a:"ইবন বায"},{t:"হিসনুল মুসলিম",a:"সাঈদ আল-কাহতানী"},{t:"রিয়াদুস সালেহীন",a:"ইমাম নববী"},{t:"তিনটি মূলনীতি",a:"মুহাম্মাদ বিন আব্দুল ওয়াহহাব"}],
  hi:[{t:"सच्चा धर्म",a:"डॉ. अबू अमीना फ़िलिप्स"},{t:"सही अक़ीदा",a:"इब्न बाज़"},{t:"हिस्नुल मुस्लिम",a:"सईद अल-क़हतानी"},{t:"रियाज़ुस सालेहीन",a:"इमाम नववी"},{t:"तीन मूल सिद्धांत",a:"मुहम्मद बिन अब्दुल वहाब"}],
};

const VD = {
  ar:[{t:"كيف نستغل شهر رمضان",c:"رمضان",e:"🌙"},{t:"أركان الإسلام الخمسة",c:"عقيدة",e:"☪️"},{t:"صفة الوضوء الصحيحة",c:"فقه",e:"💧"},{t:"سيرة النبي ﷺ",c:"سيرة",e:"✨"}],
  en:[{t:"How to Benefit from Ramadan",c:"Ramadan",e:"🌙"},{t:"Five Pillars of Islam",c:"Aqeedah",e:"☪️"},{t:"How to Perform Wudu",c:"Fiqh",e:"💧"},{t:"The Prophet's Biography ﷺ",c:"Seerah",e:"✨"}],
  tr:[{t:"Ramazandan Nasıl Faydalanılır",c:"Ramazan",e:"🌙"},{t:"İslam'ın Beş Şartı",c:"Akaid",e:"☪️"},{t:"Doğru Abdest Nasıl Alınır",c:"Fıkıh",e:"💧"},{t:"Peygamberimizin Hayatı ﷺ",c:"Siyer",e:"✨"}],
  ur:[{t:"رمضان سے کیسے فائدہ اٹھائیں",c:"رمضان",e:"🌙"},{t:"اسلام کے پانچ ارکان",c:"عقیدہ",e:"☪️"},{t:"صحیح وضو کا طریقہ",c:"فقہ",e:"💧"},{t:"نبی کریم ﷺ کی سیرت",c:"سیرت",e:"✨"}],
  ms:[{t:"Cara Memanfaatkan Ramadan",c:"Ramadan",e:"🌙"},{t:"Lima Rukun Islam",c:"Akidah",e:"☪️"},{t:"Cara Berwuduk yang Betul",c:"Fiqh",e:"💧"},{t:"Sirah Nabi ﷺ",c:"Sirah",e:"✨"}],
  fr:[{t:"Comment profiter du Ramadan",c:"Ramadan",e:"🌙"},{t:"Les cinq piliers de l'Islam",c:"Aqida",e:"☪️"},{t:"Comment faire les ablutions",c:"Fiqh",e:"💧"},{t:"La biographie du Prophète ﷺ",c:"Sira",e:"✨"}],
  fa:[{t:"چگونه از ماه رمضان بهره ببریم",c:"رمضان",e:"🌙"},{t:"پنج رکن اسلام",c:"عقیده",e:"☪️"},{t:"طریقه صحیح وضو",c:"فقه",e:"💧"},{t:"زندگینامه پیامبر ﷺ",c:"سیره",e:"✨"}],
  bn:[{t:"রমজান থেকে কীভাবে উপকৃত হবেন",c:"রমজান",e:"🌙"},{t:"ইসলামের পাঁচ স্তম্ভ",c:"আকীদা",e:"☪️"},{t:"সঠিক ওযূর পদ্ধতি",c:"ফিকহ",e:"💧"},{t:"নবী ﷺ এর জীবনী",c:"সীরাহ",e:"✨"}],
  hi:[{t:"रमज़ान से कैसे फ़ायदा उठाएं",c:"रमज़ान",e:"🌙"},{t:"इस्लाम के पाँच स्तंभ",c:"अक़ीदा",e:"☪️"},{t:"सही वुज़ू का तरीक़ा",c:"फ़िक़्ह",e:"💧"},{t:"नबी ﷺ की जीवनी",c:"सीरह",e:"✨"}],
};

export default function ManafaaHomepage() {
  const [lang, setLang] = useState("ar");
  const [showLM, setShowLM] = useState(false);
  const [slide, setSlide] = useState(0);
  const [rat, setRat] = useState(0);
  const [hRat, setHRat] = useState(0);
  const [cmt, setCmt] = useState("");
  const [scrolled, setScrolled] = useState(false);
  const [mob, setMob] = useState(false);
  const [sent, setSent] = useState(false);

  const lo = langs.find(l=>l.code===lang)||langs[0];
  const dir = lo.dir;
  const ui = T[lang]||T.ar;
  const slides = SL[lang]||SL.ar;
  const vids = VD[lang]||VD.ar;
  const books = BK[lang]||BK.ar;
  const cq = (CQ[lang]||CQ.ar)[0];
  const t = k => ui[k]||T.ar[k]||k;
  const arr = dir==="rtl"?"←":"→";

  useEffect(()=>{setSlide(0)},[lang]);
  useEffect(()=>{const i=setInterval(()=>setSlide(p=>(p+1)%3),6000);return()=>clearInterval(i)},[lang]);
  useEffect(()=>{const h=()=>setScrolled(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);

  const nav=[{k:"n_home",i:"🏠",h:"/"},{k:"n_vid",i:"🎬",h:"/videos"},{k:"n_quran",i:"📖",h:"/quran"},{k:"n_lib",i:"📚",h:"/library"},{k:"n_hajj",i:"🕋",h:"/hajj"},{k:"n_umrah",i:"🕌",h:"/umrah"},{k:"n_contest",i:"🏆",h:"/contest"}];
  const stats=[{n:"500+",k:"s_vid",i:"🎬"},{n:"200+",k:"s_book",i:"📚"},{n:"9",k:"s_lang",i:"🌍"},{n:"50K+",k:"s_visit",i:"👥"}];

  const doFeedback=async()=>{if(!rat)return;await supaIns("feedback",{rating:rat,comment:cmt||null,lang});setSent(true);setRat(0);setCmt("");setTimeout(()=>setSent(false),3000)};

  const IP=()=>(<svg className="absolute inset-0 w-full h-full opacity-[0.03]" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="ip" x="0" y="0" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M40 0L80 40L40 80L0 40Z" fill="none" stroke="currentColor" strokeWidth="0.5"/><circle cx="40" cy="40" r="15" fill="none" stroke="currentColor" strokeWidth="0.5"/><path d="M20 20L60 20L60 60L20 60Z" fill="none" stroke="currentColor" strokeWidth="0.3"/><circle cx="40" cy="40" r="28" fill="none" stroke="currentColor" strokeWidth="0.3"/></pattern></defs><rect width="100%" height="100%" fill="url(#ip)"/></svg>);

  return (
    <div dir={dir} className="min-h-screen bg-[#FAFBFC]" style={{fontFamily:"'Tajawal','Segoe UI',sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700;800;900&family=Amiri:wght@400;700&display=swap');*{box-sizing:border-box;margin:0;padding:0}:root{--p:#1B3A4B;--pl:#2C5F7C;--pd:#0F2530;--g:#C8A951;--gl:#E8D48B;--gd:#9E832E;--cr:#FFF9EE;--tx:#1a1a2e;--tl:#6B7280}@keyframes fu{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes sd{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}@keyframes fl{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes sh{0%{background-position:-200% 0}100%{background-position:200% 0}}@keyframes rs{from{transform:rotate(0)}to{transform:rotate(360deg)}}@keyframes ae{from{opacity:0;transform:scale(.95)}to{opacity:1;transform:scale(1)}}.afu{animation:fu .8s ease-out forwards}.asd{animation:sd .3s ease-out forwards}.afl{animation:fl 4s ease-in-out infinite}.aae{animation:ae .8s ease-out forwards}.gn{background:rgba(27,58,75,.95);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px)}.hg{background:linear-gradient(135deg,#0F2530 0%,#1B3A4B 30%,#2C5F7C 70%,#1B3A4B 100%)}.gs{background:linear-gradient(90deg,var(--gd),var(--g),var(--gl),var(--g),var(--gd));background-size:200% 100%;animation:sh 4s linear infinite;-webkit-background-clip:text;-webkit-text-fill-color:transparent}.ch{transition:all .4s cubic-bezier(.4,0,.2,1)}.ch:hover{transform:translateY(-8px);box-shadow:0 25px 50px -12px rgba(27,58,75,.15)}.sd2{background:linear-gradient(90deg,transparent,var(--g),transparent);height:1px}.qf{font-family:'Amiri',serif}.bp{background:linear-gradient(135deg,var(--gd),var(--g));transition:all .3s ease}.bp:hover{background:linear-gradient(135deg,var(--g),var(--gl));transform:translateY(-2px);box-shadow:0 10px 30px rgba(200,169,81,.3)}.ni{position:relative;transition:all .3s}.ni::after{content:'';position:absolute;bottom:-4px;${dir==="rtl"?"right":"left"}:0;width:0;height:2px;background:var(--g);transition:width .3s}.ni:hover::after{width:100%}.sr{cursor:pointer;transition:all .2s}.sr:hover{transform:scale(1.2)}`}</style>

      <div className="w-full py-2 text-center text-sm" style={{background:'var(--pd)',color:'var(--g)'}}>{t("bismillah")}</div>

      <nav className={`gn sticky top-0 z-50 transition-all duration-500 ${scrolled?'shadow-2xl':''}`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="flex items-center justify-between h-16 sm:h-20">
          <div className="flex items-center gap-3 flex-shrink-0"><div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full flex items-center justify-center" style={{background:'var(--g)',color:'var(--pd)'}}><span className="text-lg sm:text-xl font-bold qf">م</span></div><div className="hidden sm:block"><h1 className="text-white font-bold text-base leading-tight">{t("site_name")}</h1><p className="text-xs" style={{color:'var(--g)'}}>{t("site_desc")}</p></div></div>
          <div className="hidden lg:flex items-center gap-1">{nav.map((n,i)=><Link key={i} to={n.h} className="ni text-white/80 hover:text-white text-sm px-3 py-2 rounded-lg hover:bg-white/5 transition-all">{t(n.k)}</Link>)}</div>
          <div className="flex items-center gap-2 sm:gap-3">
            <div className="relative">
              <button onClick={()=>setShowLM(!showLM)} className="flex items-center gap-1.5 text-white/80 hover:text-white text-sm px-2.5 py-1.5 rounded-lg hover:bg-white/5 transition-all"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9"/></svg><span className="hidden sm:inline">{lo.name}</span></button>
              {showLM&&<div className={`absolute ${dir==="rtl"?"left-0":"right-0"} top-full mt-2 w-44 bg-white rounded-xl shadow-2xl border border-gray-100 overflow-hidden asd z-50`}>{langs.map(l=><button key={l.code} onClick={()=>{setLang(l.code);setShowLM(false)}} className={`w-full px-4 py-2.5 text-sm hover:bg-gray-50 transition-colors flex items-center justify-between ${lang===l.code?'bg-blue-50 font-bold':''}`} style={{textAlign:l.dir==="rtl"?"right":"left",color:lang===l.code?'var(--p)':'var(--tx)'}}><span>{l.name}</span>{lang===l.code&&<svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/></svg>}</button>)}</div>}
            </div>
            <button className="hidden sm:flex items-center gap-1.5 text-sm px-4 py-2 rounded-lg transition-all font-medium" style={{background:'var(--g)',color:'var(--pd)'}}><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>{t("login")}</button>
            <button onClick={()=>setMob(!mob)} className="lg:hidden text-white p-2 rounded-lg hover:bg-white/10"><svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">{mob?<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12"/>:<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16"/>}</svg></button>
          </div>
        </div>
        {mob&&<div className="lg:hidden pb-4 asd"><div className="bg-white/5 rounded-xl p-2">{nav.map((n,i)=><Link key={i} to={n.h} onClick={()=>setMob(false)} className="flex items-center gap-3 text-white/80 hover:text-white px-4 py-3 rounded-lg hover:bg-white/5 transition-all"><span>{n.i}</span><span>{t(n.k)}</span></Link>)}</div></div>}
        </div>
      </nav>

      <section className="hg relative overflow-hidden" style={{minHeight:'85vh'}} id="home">
        <IP/>
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 flex flex-col items-center justify-center" style={{minHeight:'85vh'}}>
          <div className="mb-8 afu" style={{animationDelay:'.2s'}}><div className="w-28 h-28 sm:w-36 sm:h-36 rounded-full flex items-center justify-center relative" style={{background:'rgba(200,169,81,.1)',border:'2px solid rgba(200,169,81,.3)'}}><div className="w-20 h-20 sm:w-28 sm:h-28 rounded-full flex items-center justify-center" style={{background:'rgba(200,169,81,.15)'}}><span className="text-4xl sm:text-5xl font-black qf" style={{color:'var(--g)'}}>{t("hero_title")}</span></div><div className="absolute inset-0 rounded-full border border-dashed opacity-20" style={{borderColor:'var(--g)',animation:'rs 30s linear infinite'}}></div></div></div>
          <div className="text-center mb-6 afu" style={{animationDelay:'.4s'}}><h2 className="text-lg sm:text-xl font-light text-white/70 mb-2">{t("hero_sub")}</h2><h1 className="text-4xl sm:text-6xl lg:text-7xl font-black gs mb-3 qf">{t("hero_title")}</h1><p className="text-base sm:text-lg text-white/60 font-light">{t("site_desc")}</p></div>
          <div className="w-full max-w-4xl mb-12 afu" style={{animationDelay:'.6s'}}><div className="relative rounded-2xl p-6 sm:p-10" style={{background:'rgba(255,255,255,.03)',border:'1px solid rgba(200,169,81,.15)'}}>
            <div className="absolute top-3 right-3 w-6 h-6 border-t-2 border-r-2 rounded-tr-lg" style={{borderColor:'var(--g)'}}></div><div className="absolute top-3 left-3 w-6 h-6 border-t-2 border-l-2 rounded-tl-lg" style={{borderColor:'var(--g)'}}></div><div className="absolute bottom-3 right-3 w-6 h-6 border-b-2 border-r-2 rounded-br-lg" style={{borderColor:'var(--g)'}}></div><div className="absolute bottom-3 left-3 w-6 h-6 border-b-2 border-l-2 rounded-bl-lg" style={{borderColor:'var(--g)'}}></div>
            <div key={`${lang}-${slide}`} className="text-center aae"><p className="text-xl sm:text-2xl lg:text-3xl leading-loose qf" style={{color:'var(--gl)'}}>{slides[slide]?.a}</p><p className="mt-4 text-sm text-white/40">{slides[slide]?.s}</p></div>
            <div className="flex justify-center gap-2 mt-6">{slides.map((_,i)=><button key={i} onClick={()=>setSlide(i)} className="h-2 rounded-full transition-all duration-300" style={{background:i===slide?'var(--g)':'rgba(255,255,255,.2)',width:i===slide?'24px':'8px'}}/>)}</div>
          </div></div>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-3 sm:gap-4 w-full max-w-3xl afu" style={{animationDelay:'.8s'}}>{[{i:"🎬",k:"n_vid"},{i:"📖",k:"n_quran"},{i:"📚",k:"n_lib"},{i:"🕋",k:"n_hajj"},{i:"🕌",k:"n_umrah"},{i:"🏆",k:"n_contest"}].map((x,i)=><button key={i} className="flex flex-col items-center gap-2 p-3 sm:p-4 rounded-xl transition-all hover:scale-105" style={{background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.08)'}}><span className="text-2xl sm:text-3xl">{x.i}</span><span className="text-xs sm:text-sm text-white/70">{t(x.k)}</span></button>)}</div>
          <div className="absolute bottom-8 left-1/2 -translate-x-1/2"><div className="w-6 h-10 rounded-full border-2 border-white/20 flex items-start justify-center p-1.5"><div className="w-1.5 h-3 rounded-full bg-white/40" style={{animation:'fl 2s ease-in-out infinite'}}></div></div></div>
        </div>
      </section>

      <section className="relative -mt-12 z-20 max-w-5xl mx-auto px-4 sm:px-6"><div className="bg-white rounded-2xl shadow-xl p-6 sm:p-8 grid grid-cols-2 sm:grid-cols-4 gap-6">{stats.map((s,i)=><div key={i} className="text-center"><span className="text-3xl mb-2 block">{s.i}</span><div className="text-2xl sm:text-3xl font-black" style={{color:'var(--p)'}}>{s.n}</div><div className="text-sm mt-1" style={{color:'var(--tl)'}}>{t(s.k)}</div></div>)}</div></section>

      <section className="py-20 sm:py-28 max-w-7xl mx-auto px-4 sm:px-6" id="videos">
        <div className="text-center mb-12"><div className="flex items-center justify-center gap-4 mb-4"><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div><span className="text-sm font-medium tracking-widest" style={{color:'var(--g)'}}>{t("vid_tag")}</span><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div></div><h2 className="text-3xl sm:text-4xl font-black" style={{color:'var(--p)'}}>{t("vid_title")}</h2><p className="mt-3 text-base" style={{color:'var(--tl)'}}>{t("vid_desc")}</p></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{vids.map((v,i)=><div key={i} className="ch group rounded-2xl overflow-hidden bg-white shadow-md cursor-pointer"><div className="relative h-48 flex items-center justify-center" style={{background:'var(--p)'}}><span className="text-6xl opacity-30">{v.e}</span><div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all duration-300"><div className="w-14 h-14 rounded-full flex items-center justify-center shadow-lg" style={{background:'var(--g)'}}><svg className="w-6 h-6" style={{marginInlineStart:'2px'}} fill="white" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg></div></div><div className={`absolute top-3 ${dir==="rtl"?"right-3":"left-3"} px-3 py-1 rounded-full text-xs font-medium text-white`} style={{background:'rgba(200,169,81,.9)'}}>{v.c}</div></div><div className="p-4"><h3 className="font-bold text-sm leading-relaxed" style={{color:'var(--tx)'}}>{v.t}</h3></div></div>)}</div>
        <div className="text-center mt-10"><button className="bp px-8 py-3 rounded-xl text-white font-bold text-sm">{t("vid_all")} {arr}</button></div>
      </section>

      <div className="sd2 max-w-xs mx-auto"></div>

      <section className="py-20 sm:py-28 relative overflow-hidden" style={{background:'var(--cr)'}} id="quran"><IP/><div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6"><div className="text-center mb-12"><div className="flex items-center justify-center gap-4 mb-4"><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div><span className="text-sm font-medium tracking-widest" style={{color:'var(--g)'}}>{t("q_tag")}</span><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div></div><h2 className="text-3xl sm:text-4xl font-black" style={{color:'var(--p)'}}>{t("q_title")}</h2><p className="mt-3 text-base" style={{color:'var(--tl)'}}>{t("q_desc")}</p></div><div className="max-w-2xl mx-auto bg-white rounded-3xl shadow-xl overflow-hidden" style={{border:'1px solid rgba(200,169,81,.2)'}}><div className="p-8 sm:p-12 text-center" style={{background:'linear-gradient(135deg,var(--pd),var(--p))'}}><p className="text-sm mb-4" style={{color:'var(--g)'}}>{t("q_fatiha")}</p><div className="qf text-2xl sm:text-3xl leading-[2.5] text-white/90 space-y-2"><p>بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ</p><p>الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ</p><p>الرَّحْمَنِ الرَّحِيمِ</p><p>مَالِكِ يَوْمِ الدِّينِ</p></div></div><div className="p-6 text-center"><button className="bp px-8 py-3 rounded-xl text-white font-bold text-sm">{t("q_browse")} {arr}</button></div></div></div></section>

      <section className="py-20 sm:py-28 max-w-7xl mx-auto px-4 sm:px-6" id="hajj"><div className="text-center mb-12"><div className="flex items-center justify-center gap-4 mb-4"><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div><span className="text-sm font-medium tracking-widest" style={{color:'var(--g)'}}>{t("m_tag")}</span><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div></div><h2 className="text-3xl sm:text-4xl font-black" style={{color:'var(--p)'}}>{t("hu_title")}</h2><p className="mt-3 text-base" style={{color:'var(--tl)'}}>{t("hu_desc")}</p></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="ch rounded-3xl overflow-hidden shadow-lg relative" style={{minHeight:'380px',background:'linear-gradient(135deg,#0F2530,#1B3A4B)'}}><IP/><div className="relative z-10 p-8 sm:p-10 h-full flex flex-col justify-between"><div><div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-6" style={{background:'rgba(200,169,81,.15)'}}><span className="text-3xl">🕋</span></div><h3 className="text-2xl sm:text-3xl font-black text-white mb-3">{t("h_guide")}</h3><p className="text-white/60 leading-relaxed text-sm">{t("h_gdesc")}</p></div><div className="mt-8"><button className="bp px-6 py-3 rounded-xl text-white font-bold text-sm">{t("h_start")} {arr}</button></div></div></div>
          <div id="umrah" className="ch rounded-3xl overflow-hidden shadow-lg relative" style={{minHeight:'380px',background:'linear-gradient(135deg,#1B3A4B,#2C5F7C)'}}><IP/><div className="relative z-10 p-8 sm:p-10 h-full flex flex-col justify-between"><div><div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-6" style={{background:'rgba(200,169,81,.15)'}}><span className="text-3xl">🕌</span></div><h3 className="text-2xl sm:text-3xl font-black text-white mb-3">{t("u_guide")}</h3><p className="text-white/60 leading-relaxed text-sm">{t("u_gdesc")}</p></div><div className="mt-8"><button className="bp px-6 py-3 rounded-xl text-white font-bold text-sm">{t("u_start")} {arr}</button></div></div></div>
        </div>
      </section>

      <div className="sd2 max-w-xs mx-auto"></div>

      <section className="py-20 sm:py-28 max-w-7xl mx-auto px-4 sm:px-6" id="library"><div className="text-center mb-12"><div className="flex items-center justify-center gap-4 mb-4"><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div><span className="text-sm font-medium tracking-widest" style={{color:'var(--g)'}}>{t("l_tag")}</span><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div></div><h2 className="text-3xl sm:text-4xl font-black" style={{color:'var(--p)'}}>{t("l_title")}</h2><p className="mt-3 text-base" style={{color:'var(--tl)'}}>{t("l_desc")}</p></div>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-5">{books.map((b,i)=><div key={i} className="ch bg-white rounded-2xl shadow-md overflow-hidden group cursor-pointer"><div className="h-52 flex items-center justify-center relative" style={{background:`linear-gradient(135deg,${i%2===0?'var(--pd)':'var(--pl)'},var(--p))`}}><span className="text-5xl opacity-20">📖</span><div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all" style={{background:'rgba(200,169,81,.9)'}}><span className="text-white text-sm font-bold">{t("l_read")}</span></div></div><div className="p-4"><h4 className="font-bold text-sm mb-1" style={{color:'var(--tx)'}}>{b.t}</h4><p className="text-xs" style={{color:'var(--tl)'}}>{b.a}</p></div></div>)}</div>
        <div className="text-center mt-10"><button className="bp px-8 py-3 rounded-xl text-white font-bold text-sm">{t("l_all")} {arr}</button></div>
      </section>

      <section className="py-20 sm:py-28 relative overflow-hidden" style={{background:'var(--p)'}} id="contest"><IP/><div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 text-center"><div className="flex items-center justify-center gap-4 mb-4"><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div><span className="text-sm font-medium tracking-widest" style={{color:'var(--g)'}}>{t("c_tag")}</span><div className="h-px w-16 sm:w-24" style={{background:'var(--g)'}}></div></div><h2 className="text-3xl sm:text-4xl font-black text-white mb-3">{t("c_title")}</h2><p className="text-white/60 mb-10">{t("c_desc")}</p>
        <div className="bg-white rounded-3xl p-8 sm:p-10 shadow-2xl" style={{textAlign:dir==="rtl"?"right":"left"}}><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:'rgba(200,169,81,.1)'}}><span className="text-xl">❓</span></div><div><p className="text-xs" style={{color:'var(--tl)'}}>{t("c_qlabel")}</p><p className="font-bold text-sm" style={{color:'var(--p)'}}>{cq.q}</p></div></div>
          <div className="space-y-3 mb-6">{[{l:cq.a,k:"a"},{l:cq.b,k:"b"},{l:cq.c,k:"c"}].map((o,i)=><button key={i} className="w-full px-5 py-3.5 rounded-xl border-2 transition-all hover:border-current text-sm font-medium" style={{textAlign:dir==="rtl"?"right":"left",borderColor:o.k===cq.x?'var(--g)':'#E5E7EB',background:o.k===cq.x?'rgba(200,169,81,.05)':'white',color:o.k===cq.x?'var(--gd)':'var(--tx)'}}>{o.l}</button>)}</div>
          <button className="bp w-full py-3.5 rounded-xl text-white font-bold text-sm">{t("c_now")} {arr}</button>
        </div></div></section>

      <section className="py-20 sm:py-28 max-w-3xl mx-auto px-4 sm:px-6"><div className="text-center mb-10"><h2 className="text-3xl sm:text-4xl font-black" style={{color:'var(--p)'}}>{t("f_title")}</h2><p className="mt-3 text-base" style={{color:'var(--tl)'}}>{t("f_desc")}</p></div>
        <div className="bg-white rounded-3xl shadow-xl p-8 sm:p-10" style={{border:'1px solid rgba(200,169,81,.15)'}}>
          {sent?<div className="text-center py-8"><span className="text-5xl block mb-4">✅</span><p className="text-lg font-bold" style={{color:'var(--p)'}}>{t("f_thx")}</p></div>:<>
            <div className="flex justify-center gap-2 mb-8">{[1,2,3,4,5].map(s=><button key={s} onClick={()=>setRat(s)} onMouseEnter={()=>setHRat(s)} onMouseLeave={()=>setHRat(0)} className="sr text-3xl sm:text-4xl" style={{color:s<=(hRat||rat)?'var(--g)':'#D1D5DB'}}>{s<=(hRat||rat)?"★":"☆"}</button>)}</div>
            <textarea value={cmt} onChange={e=>setCmt(e.target.value)} placeholder={t("f_ph")} className="w-full h-32 rounded-xl border-2 p-4 text-sm resize-none focus:outline-none transition-colors" style={{borderColor:'#E5E7EB',fontFamily:'Tajawal,sans-serif',direction:dir,textAlign:dir==="rtl"?"right":"left"}} onFocus={e=>e.target.style.borderColor='var(--g)'} onBlur={e=>e.target.style.borderColor='#E5E7EB'}/>
            <button onClick={doFeedback} className="bp w-full mt-4 py-3.5 rounded-xl text-white font-bold text-sm">{t("f_send")}</button>
          </>}
        </div>
      </section>

      <footer style={{background:'var(--pd)'}}><div className="max-w-7xl mx-auto px-4 sm:px-6 py-16"><div className="grid grid-cols-1 md:grid-cols-3 gap-10">
        <div><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-full flex items-center justify-center" style={{background:'var(--g)',color:'var(--pd)'}}><span className="font-bold qf">م</span></div><div><h3 className="text-white font-bold">{t("site_name")}</h3><p className="text-xs" style={{color:'var(--g)'}}>{t("site_desc")}</p></div></div><p className="text-white/50 text-sm leading-relaxed">{t("ft_about")}</p></div>
        <div><h4 className="text-white font-bold mb-4">{t("ft_links")}</h4><div className="space-y-2">{nav.map((n,i)=><Link key={i} to={n.h} className="block text-white/50 hover:text-white text-sm transition-colors">{t(n.k)}</Link>)}</div></div>
        <div><h4 className="text-white font-bold mb-4">{t("ft_langs")}</h4><div className="flex flex-wrap gap-2">{langs.map(l=><button key={l.code} onClick={()=>setLang(l.code)} className="text-xs px-3 py-1.5 rounded-full transition-all" style={{background:lang===l.code?'var(--g)':'rgba(255,255,255,.05)',color:lang===l.code?'var(--pd)':'rgba(255,255,255,.6)',fontWeight:lang===l.code?'bold':'normal'}}>{l.name}</button>)}</div></div>
      </div><div className="mt-12 pt-8 text-center" style={{borderTop:'1px solid rgba(255,255,255,.05)'}}><p className="text-white/30 text-sm">© {new Date().getFullYear()} {t("ft_copy")}</p></div></div></footer>

      {(showLM||mob)&&<div className="fixed inset-0 z-40" onClick={()=>{setShowLM(false);setMob(false)}}></div>}
    </div>
  );
}
