import { useNavigate, Link } from "react-router-dom";
import { supaInsert as supaIns } from "../lib/supabase";
import { useState, useEffect } from "react";

const L=[{c:"ar",n:"العربية",d:"rtl"},{c:"en",n:"English",d:"ltr"},{c:"tr",n:"Türkçe",d:"ltr"},{c:"ur",n:"اردو",d:"rtl"},{c:"ms",n:"Melayu",d:"ltr"},{c:"fr",n:"Français",d:"ltr"},{c:"fa",n:"فارسی",d:"rtl"},{c:"bn",n:"বাংলা",d:"ltr"},{c:"hi",n:"हिन्दी",d:"ltr"}];

const T={
ar:{bismillah:"بسم الله الرحمن الرحيم",site_name:"مشروع منافع",site_desc:"لدعوة الحجاج والمعتمرين",n_home:"الرئيسية",n_vid:"الفيديوهات",n_quran:"القرآن الكريم",n_lib:"المكتبة",n_hajj:"الحج",n_umrah:"العمرة",n_contest:"المسابقة",login:"تسجيل الدخول",hero_title:"العمرة زيارة بيت الله",hero_desc:"العمرة سُنة مؤكدة وقربة عظيمة إلى الله تعالى، تُشرع في أي وقت من العام. قال ﷺ: العمرة إلى العمرة كفارة لما بينهما",journey_title:"رحلة المعتمر",journey_desc:"خطواتك من الإحرام حتى الحلق أو التقصير",start_journey:"ابدأ الرحلة",about_title:"معلومات عن العمرة",virtues_title:"فضائل العمرة",pillars_title:"أركان العمرة",pillars_desc:"أركان العمرة ثلاثة لا تصح العمرة إلا بها",obligations_title:"واجبات العمرة",obligations_desc:"واجبات العمرة اثنان — من ترك واحداً منهما وجب عليه دم",sunnahs_title:"سنن ومستحبات العمرة",miqaat_title:"المواقيت المكانية",remember_title:"أمور يجب أن تتذكرها",prohibitions_title:"محظورات الإحرام",step:"الخطوة",of:"من",dua:"الدعاء",prev:"السابق",next:"التالي",back_map:"العودة للخريطة",no_content:"لا يوجد محتوى بهذه اللغة حالياً — سيتم إضافته قريباً",ft_copy:"مشروع منافع — جميع الحقوق محفوظة",ft_langs:"اللغات المدعومة",
  virtues:["العمرة إلى العمرة كفارة لما بينهما — والحج المبرور ليس له جزاء إلا الجنة","عمرة في رمضان تعدل حجة — أو قال: حجة معي (مع النبي ﷺ)","تابعوا بين الحج والعمرة فإنهما ينفيان الفقر والذنوب كما ينفي الكير خبث الحديد","العمار والحجاج وفد الله — دعاهم فأجابوه وسألوه فأعطاهم"],
  pillars:[{t:"الإحرام",d:"نية الدخول في النسك بالقلب والتلفظ بها: لبيك اللهم عمرة. وهو ركن بإجماع العلماء — لا تنعقد العمرة بدونه"},{t:"الطواف بالبيت",d:"الطواف بالكعبة سبعة أشواط كاملة، يبدأ من الحجر الأسود وينتهي إليه. يجعل البيت عن يساره"},{t:"السعي بين الصفا والمروة",d:"سبعة أشواط تبدأ من الصفا وتنتهي بالمروة. يدعو على كل من الصفا والمروة"}],
  obligations:[{t:"الإحرام من الميقات",d:"يجب الإحرام من الميقات المحدد لكل بلد — ومن تجاوز الميقات بلا إحرام وجب عليه الرجوع أو ذبح فدية"},{t:"الحلق أو التقصير",d:"حلق شعر الرأس بالكامل أو تقصيره للرجل (الحلق أفضل)، وتقصير قدر أنملة للمرأة"}],
  sunnahs:["تقليم الأظافر وإزالة شعر العانة والإبط قبل الإحرام","الاغتسال قبل الإحرام","التطيب في البدن (لا في ملابس الإحرام)","التلبية بصوت مرتفع للرجال","الاضطباع في الطواف: كشف الكتف الأيمن","الرمل في الأشواط الثلاثة الأولى من الطواف","استلام الحجر الأسود وتقبيله إن تيسر","صلاة ركعتين خلف مقام إبراهيم بعد الطواف","الشرب من ماء زمزم والدعاء","الإسراع بين العلامتين الخضراوين في السعي (للرجال)","الاشتراط عند الإحرام: اللهم إن حبسني حابس فمحلي حيث حبستني"],
  prohibitions:["قص الشعر أو تقليم الأظافر","استعمال الطيب بعد الإحرام","لبس المخيط للرجل (القميص، البنطال...)","تغطية الرأس للرجل","لبس النقاب والقفازين للمرأة","الجماع ومقدماته","عقد النكاح","صيد البر"],
  miqaat_places:["ذو الحليفة (أبيار علي) — ميقات أهل المدينة — أبعد المواقيت عن مكة","الجحفة (رابغ) — ميقات أهل الشام ومصر والمغرب","قرن المنازل (السيل الكبير) — ميقات أهل نجد والطائف","يلملم (السعدية) — ميقات أهل اليمن وتهامة","ذات عرق — ميقات أهل العراق وخراسان","لمن كان داخل مكة: يُحرم من التنعيم أو عائشة"],
  remember:["العمرة واجبة مرة في العمر عند جمهور العلماء","يمكن أداؤها في أي وقت من السنة — وأفضلها في رمضان","تعلم أحكام العمرة قبل السفر واستشر أهل العلم","تأكد من صحة وثائقك وتأشيرتك","حافظ على الهدوء والسكينة في الطواف والسعي","ادعُ الله بما شئت واغتنم القرب من البيت الحرام","المرأة الحائض لا تطوف حتى تطهر لكن يجوز لها السعي عند بعض العلماء"],
},
en:{bismillah:"In the Name of Allah, the Most Gracious, the Most Merciful",site_name:"Manafea Project",site_desc:"For Hajj & Umrah Dawah",n_home:"Home",n_vid:"Videos",n_quran:"Holy Quran",n_lib:"Library",n_hajj:"Hajj",n_umrah:"Umrah",n_contest:"Contest",login:"Login",hero_title:"Umrah: Visiting the House of Allah",hero_desc:"Umrah is a highly recommended act of worship and a great means of drawing closer to Allah. It can be performed any time of year. The Prophet ﷺ said: Umrah to Umrah is expiation for what is between them",journey_title:"The Pilgrim's Journey",journey_desc:"Your steps from Ihram to shaving or trimming",start_journey:"Start the Journey",about_title:"About Umrah",virtues_title:"Virtues of Umrah",pillars_title:"Pillars of Umrah",pillars_desc:"Three pillars without which Umrah is invalid",obligations_title:"Obligations of Umrah",obligations_desc:"Two obligations — leaving one requires a sacrifice (dam)",sunnahs_title:"Sunnahs of Umrah",miqaat_title:"Spatial Miqats",remember_title:"Things to Remember",prohibitions_title:"Ihram Prohibitions",step:"Step",of:"of",dua:"Supplication",prev:"Previous",next:"Next",back_map:"Back to Map",no_content:"No content available in this language yet — coming soon",ft_copy:"Manafea Project — All Rights Reserved",ft_langs:"Supported Languages",
  virtues:["Umrah to Umrah is expiation for what is between them, and an accepted Hajj has no reward except Paradise","Umrah in Ramadan equals a Hajj — or he said: a Hajj with me (with the Prophet ﷺ)","Alternate between Hajj and Umrah, for they remove poverty and sins as the bellows remove impurities from iron","The performers of Hajj and Umrah are the delegation of Allah — He called them and they responded, they asked Him and He gave them"],
  pillars:[{t:"Ihram",d:"The intention to enter the sacred state, declared by heart and tongue: Labbayk Allahumma Umrah. A pillar by consensus — Umrah is not valid without it"},{t:"Tawaf around the Ka'bah",d:"Seven complete circuits around the Ka'bah, starting from the Black Stone and ending at it, keeping the Ka'bah to your left"},{t:"Sa'i between Safa and Marwah",d:"Seven circuits starting from Safa and ending at Marwah, supplicating at each hill"}],
  obligations:[{t:"Ihram from the Miqat",d:"One must enter Ihram at the designated Miqat — passing without Ihram requires returning or offering a sacrifice"},{t:"Shaving or Trimming Hair",d:"Men shave completely or trim (shaving preferred). Women trim a fingertip's length"}],
  sunnahs:["Clipping nails and removing body hair before Ihram","Bathing (Ghusl) before entering Ihram","Applying fragrance to the body (not the Ihram garments)","Reciting Talbiyah aloud (for men)","Idtiba during Tawaf: uncovering the right shoulder","Raml (walking briskly) in the first three circuits of Tawaf","Touching and kissing the Black Stone if possible","Praying two rak'ahs behind Maqam Ibrahim after Tawaf","Drinking Zamzam water and making dua","Walking briskly between the green markers during Sa'i (for men)","Making the conditional statement at Ihram: O Allah, if anything prevents me, my place of ending is where You stop me"],
  prohibitions:["Cutting hair or clipping nails","Using fragrance after entering Ihram","Wearing stitched garments for men","Covering the head for men","Wearing niqab and gloves for women","Intimate relations and their precursors","Contracting marriage","Hunting land animals"],
  miqaat_places:["Dhul-Hulayfah (Abyar Ali) — Miqat for Madinah — the farthest from Makkah","Al-Juhfah (Rabigh) — Miqat for Sham, Egypt, and North Africa","Qarn Al-Manazil (As-Sayl Al-Kabir) — Miqat for Najd and Taif","Yalamlam (As-Sadiyah) — Miqat for Yemen","Dhat Irq — Miqat for Iraq and Khorasan","For those inside Makkah: enter Ihram from Tan'eem or Masjid Aisha"],
  remember:["Umrah is obligatory once in a lifetime according to the majority of scholars","It can be performed any time of year — best in Ramadan","Learn Umrah rulings before traveling and consult scholars","Verify your documents and visa","Maintain calm and tranquility during Tawaf and Sa'i","Supplicate abundantly and seize the blessing of being near the Sacred House","A menstruating woman does not perform Tawaf until she is pure, but some scholars permit Sa'i"],
},
tr:{bismillah:"Rahman ve Rahim olan Allah'ın adıyla",site_name:"Menafi Projesi",site_desc:"Hacılar İçin",n_home:"Ana Sayfa",n_vid:"Videolar",n_quran:"Kur'an",n_lib:"Kütüphane",n_hajj:"Hac",n_umrah:"Umre",n_contest:"Yarışma",login:"Giriş",hero_title:"Umre: Allah'ın Evini Ziyaret",hero_desc:"Umre, Allah'a yakınlaşmanın büyük bir yoludur. Yılın her zamanında yapılabilir",journey_title:"Umrecinin Yolculuğu",journey_desc:"İhramdan traşa kadar adımlarınız",start_journey:"Yolculuğa Başla",about_title:"Umre Hakkında",virtues_title:"Umrenin Faziletleri",pillars_title:"Umrenin Rükünleri",pillars_desc:"Üç rükün — bunlarsız umre geçerli değildir",obligations_title:"Umrenin Vacipleri",obligations_desc:"İki vacip — birini terk eden kurban kesmeli",sunnahs_title:"Umrenin Sünnetleri",miqaat_title:"Mekansal Mikatlar",remember_title:"Hatırlanması Gerekenler",prohibitions_title:"İhram Yasakları",step:"Adım",of:"/",dua:"Dua",prev:"Önceki",next:"Sonraki",back_map:"Haritaya Dön",no_content:"Bu dilde içerik yok — yakında",ft_copy:"Menafi — Hakları Saklıdır",ft_langs:"Diller",
  virtues:["Umreden umreye aradaki günahlara kefaret","Ramazanda umre hacca eşittir","Hac ve umreyi peş peşe yapın — fakirlik ve günahı giderirler","Umreciler Allah'ın misafirleridir"],
  pillars:[{t:"İhram",d:"Nüsüke niyet etmek"},{t:"Kâbe'yi Tavaf",d:"Yedi şavt — Hacer-i Esved'den başlar"},{t:"Safa-Merve Sa'y",d:"Yedi şavt — Safa'dan başlar Merve'de biter"}],
  obligations:[{t:"Mikattan İhram",d:"Belirlenen mikattan ihrama girmek"},{t:"Traş veya Kısaltma",d:"Erkek traş olur veya kısaltır, kadın bir parmak ucu kadar keser"}],
  sunnahs:["İhramdan önce tırnak kesmek","İhramdan önce gusül","Bedene güzel koku sürmek","Erkeklerin telbiyeyi yüksek sesle okuması","Tavafta ıztıba yapmak","İlk üç şavtta remel","Hacer-i Esved'i öpmek","Tavaftan sonra Makam-ı İbrahim'de iki rekât","Zemzem suyu içmek","Sa'y'de yeşil işaretler arasında hızlı yürümek","İhramda şart koşmak"],
  prohibitions:["Saç kesmek veya tırnak kesmek","İhramdan sonra koku sürmek","Erkeklerin dikişli giysi giymesi","Erkeklerin başını örtmesi","Kadınların peçe ve eldiven takması","Cinsel ilişki","Nikah akdi","Kara avı"],
  miqaat_places:["Zülhuleyfe — Medine mikatı","Cuhfe (Rabığ) — Şam mikatı","Karnülmenazil — Necid mikatı","Yelemlem — Yemen mikatı","Zatüırk — Irak mikatı","Mekke'dekiler: Ten'im'den ihrama girer"],
  remember:["Umre ömürde bir kez vaciptir","Yılın her zamanı yapılabilir — en faziletlisi Ramazan'da","Hükümlerini öğrenin","Belgelerinizi kontrol edin","Tavaf ve sa'y'de sakin olun","Bol bol dua edin","Hayızlı kadın temizlenene kadar tavaf edemez"],
},
ur:{bismillah:"اللہ کے نام سے",site_name:"منافع",site_desc:"حاجیوں کی دعوت",n_home:"ہوم",n_vid:"ویڈیوز",n_quran:"قرآن",n_lib:"لائبریری",n_hajj:"حج",n_umrah:"عمرہ",n_contest:"مقابلہ",login:"لاگ ان",hero_title:"عمرہ: بیت اللہ کی زیارت",hero_desc:"عمرہ ایک عظیم عبادت ہے جو سال بھر کسی بھی وقت ادا کی جا سکتی ہے",journey_title:"عمرے کا سفر",journey_desc:"احرام سے حلق تک مراحل",start_journey:"سفر شروع کریں",about_title:"عمرہ کے بارے میں",virtues_title:"عمرہ کے فضائل",pillars_title:"عمرہ کے ارکان",pillars_desc:"تین ارکان جن کے بغیر عمرہ صحیح نہیں",obligations_title:"عمرہ کے واجبات",obligations_desc:"دو واجبات — ترک پر دم واجب",sunnahs_title:"عمرہ کی سنتیں",miqaat_title:"میقات",remember_title:"یاد رکھنے کی باتیں",prohibitions_title:"احرام کی ممانعتیں",step:"مرحلہ",of:"میں سے",dua:"دعا",prev:"پچھلا",next:"اگلا",back_map:"واپس",no_content:"ابھی مواد نہیں",ft_copy:"منافع — حقوق محفوظ",ft_langs:"زبانیں",
  virtues:["عمرہ سے عمرہ درمیان کے گناہوں کا کفارہ","رمضان میں عمرہ حج کے برابر","حج اور عمرہ فقر اور گناہ دور کرتے ہیں","عمرہ کرنے والے اللہ کے مہمان ہیں"],
  pillars:[{t:"احرام",d:"نسک میں داخل ہونے کی نیت"},{t:"طواف",d:"کعبے کے سات چکر"},{t:"سعی",d:"صفا اور مروہ کے درمیان سات چکر"}],
  obligations:[{t:"میقات سے احرام",d:"مقررہ میقات سے احرام باندھنا"},{t:"حلق یا قصر",d:"مرد سر منڈوائے یا بال چھوٹے کرے، عورت انگلی کے پور بھر کاٹے"}],
  sunnahs:["احرام سے پہلے ناخن کاٹنا","غسل کرنا","خوشبو لگانا","بلند آواز سے تلبیہ","اضطباع","رمل","حجر اسود کو بوسہ","مقام ابراہیم کے پیچھے دو رکعت","زمزم پینا","سبز نشانیوں کے درمیان تیز چلنا","اشتراط"],
  prohibitions:["بال کاٹنا یا ناخن تراشنا","خوشبو لگانا","مردوں کا سلا ہوا کپڑا","مردوں کا سر ڈھانپنا","عورتوں کا نقاب اور دستانے","جماع","نکاح","زمینی شکار"],
  miqaat_places:["ذوالحلیفہ — مدینہ","جحفہ — شام","قرن المنازل — نجد","یلملم — یمن","ذات عرق — عراق","مکہ والے: تنعیم سے احرام"],
  remember:["عمرہ عمر میں ایک بار واجب ہے","سال بھر ادا ہو سکتی ہے — رمضان میں افضل","احکام سیکھیں","دستاویزات چیک کریں","طواف اور سعی میں پرسکون رہیں","کثرت سے دعا کریں","حائضہ طہارت تک طواف نہیں کر سکتی"],
},
ms:{bismillah:"Dengan nama Allah",site_name:"Projek Manafea",site_desc:"Dakwah Umrah",n_home:"Utama",n_vid:"Video",n_quran:"Al-Quran",n_lib:"Perpustakaan",n_hajj:"Haji",n_umrah:"Umrah",n_contest:"Pertandingan",login:"Log Masuk",hero_title:"Umrah: Ziarah ke Baitullah",hero_desc:"Umrah ialah ibadat yang sangat digalakkan dan boleh dilakukan pada bila-bila masa",journey_title:"Perjalanan Umrah",journey_desc:"Langkah dari Ihram hingga mencukur",start_journey:"Mulakan",about_title:"Tentang Umrah",virtues_title:"Keutamaan Umrah",pillars_title:"Rukun Umrah",pillars_desc:"Tiga rukun wajib",obligations_title:"Wajib Umrah",obligations_desc:"Dua perkara wajib",sunnahs_title:"Sunat Umrah",miqaat_title:"Miqat",remember_title:"Perkara Perlu Diingat",prohibitions_title:"Larangan Ihram",step:"Langkah",of:"daripada",dua:"Doa",prev:"Sebelum",next:"Seterusnya",back_map:"Kembali",no_content:"Tiada kandungan",ft_copy:"Manafea — Hak Cipta",ft_langs:"Bahasa",
  virtues:["Umrah ke umrah menghapus dosa antara keduanya","Umrah di Ramadan sama dengan haji","Haji dan umrah menghilangkan kemiskinan dan dosa","Jemaah umrah adalah tetamu Allah"],
  pillars:[{t:"Ihram",d:"Niat memasuki ibadah"},{t:"Tawaf",d:"Tujuh pusingan mengelilingi Kaabah"},{t:"Saie",d:"Tujuh pusingan antara Safa dan Marwah"}],
  obligations:[{t:"Ihram dari Miqat",d:"Wajib berniat dari miqat yang ditetapkan"},{t:"Mencukur atau Memendekkan Rambut",d:"Lelaki mencukur atau memendekkan, wanita memotong sedikit"}],
  sunnahs:["Memotong kuku sebelum ihram","Mandi sebelum ihram","Memakai wangian pada badan","Membaca talbiah dengan suara kuat","Idtiba semasa tawaf","Ramal pada tiga pusingan pertama","Mencium Hajar Aswad","Solat dua rakaat di belakang Maqam Ibrahim","Minum air Zamzam","Berjalan pantas antara tanda hijau","Membuat syarat ihram"],
  prohibitions:["Memotong rambut atau kuku","Memakai wangian selepas ihram","Memakai pakaian berjahit bagi lelaki","Menutup kepala bagi lelaki","Memakai purdah dan sarung tangan bagi wanita","Bersetubuh","Akad nikah","Memburu binatang darat"],
  miqaat_places:["Zulhulaifah — Miqat Madinah","Juhfah — Miqat Syam","Qarnul Manazil — Miqat Najd","Yalamlam — Miqat Yaman","Zat Irq — Miqat Iraq","Penduduk Makkah: dari Tan'eem"],
  remember:["Umrah wajib sekali seumur hidup","Boleh dilakukan pada bila-bila masa","Pelajari hukumnya sebelum pergi","Semak dokumen","Kekal tenang","Banyak berdoa","Wanita haid tidak boleh tawaf sehingga suci"],
},
fr:{bismillah:"Au nom d'Allah",site_name:"Projet Manafea",site_desc:"Dawah Omra",n_home:"Accueil",n_vid:"Vidéos",n_quran:"Coran",n_lib:"Bibliothèque",n_hajj:"Hajj",n_umrah:"Omra",n_contest:"Concours",login:"Connexion",hero_title:"Omra: Visite de la Maison d'Allah",hero_desc:"La Omra est un acte d'adoration recommandé, réalisable à tout moment de l'année",journey_title:"Le Voyage du Pèlerin",journey_desc:"Vos étapes de l'Ihram au rasage",start_journey:"Commencer",about_title:"À Propos",virtues_title:"Mérites de la Omra",pillars_title:"Piliers de la Omra",pillars_desc:"Trois piliers obligatoires",obligations_title:"Obligations de la Omra",obligations_desc:"Deux obligations — en négliger une nécessite un sacrifice",sunnahs_title:"Sunnas de la Omra",miqaat_title:"Miqats Spatiaux",remember_title:"À Retenir",prohibitions_title:"Interdictions de l'Ihram",step:"Étape",of:"sur",dua:"Invocation",prev:"Précédent",next:"Suivant",back_map:"Retour",no_content:"Pas de contenu",ft_copy:"Manafea — Droits Réservés",ft_langs:"Langues",
  virtues:["Omra à Omra expie les péchés entre les deux","Omra en Ramadan équivaut à un Hajj","Hajj et Omra éliminent pauvreté et péchés","Les pèlerins sont les invités d'Allah"],
  pillars:[{t:"Ihram",d:"L'intention d'entrer en état sacré"},{t:"Tawaf",d:"Sept tours autour de la Ka'bah"},{t:"Sa'i",d:"Sept parcours entre Safa et Marwah"}],
  obligations:[{t:"Ihram au Miqat",d:"Entrer en Ihram au lieu désigné"},{t:"Rasage ou Raccourcissement",d:"Rasage ou raccourcissement pour les hommes, légère coupe pour les femmes"}],
  sunnahs:["Couper les ongles avant l'Ihram","Se laver avant l'Ihram","Se parfumer le corps","Réciter la Talbiyah à voix haute","Idtiba pendant le Tawaf","Raml dans les trois premiers tours","Embrasser la Pierre Noire","Prier deux rak'ahs derrière Maqam Ibrahim","Boire l'eau de Zamzam","Marcher vite entre les repères verts","Faire le vœu conditionnel"],
  prohibitions:["Couper cheveux ou ongles","Utiliser du parfum après l'Ihram","Porter des vêtements cousus (hommes)","Couvrir la tête (hommes)","Porter le niqab et gants (femmes)","Relations intimes","Contrat de mariage","Chasse terrestre"],
  miqaat_places:["Dhul-Hulayfah — Miqat de Médine","Al-Juhfah — Miqat du Levant","Qarn Al-Manazil — Miqat du Najd","Yalamlam — Miqat du Yémen","Dhat Irq — Miqat de l'Irak","Résidents de La Mecque: depuis Tan'eem"],
  remember:["Omra obligatoire une fois dans la vie","Possible toute l'année — meilleure en Ramadan","Apprendre les règles avant le voyage","Vérifier les documents","Rester calme","Supplier abondamment","Femme en période menstruelle: pas de Tawaf jusqu'à la purification"],
},
fa:{bismillah:"به نام خداوند",site_name:"پروژه منافع",site_desc:"دعوت معتمرین",n_home:"خانه",n_vid:"ویدیوها",n_quran:"قرآن",n_lib:"کتابخانه",n_hajj:"حج",n_umrah:"عمره",n_contest:"مسابقه",login:"ورود",hero_title:"عمره: زیارت خانه خدا",hero_desc:"عمره عبادتی بزرگ است که در هر زمانی از سال انجام می‌شود",journey_title:"سفر معتمر",journey_desc:"گام به گام از احرام تا تراشیدن",start_journey:"شروع",about_title:"درباره عمره",virtues_title:"فضائل عمره",pillars_title:"ارکان عمره",pillars_desc:"سه رکن اجباری",obligations_title:"واجبات عمره",obligations_desc:"دو واجب",sunnahs_title:"سنت‌های عمره",miqaat_title:"میقات‌ها",remember_title:"نکات مهم",prohibitions_title:"ممنوعیات احرام",step:"مرحله",of:"از",dua:"دعا",prev:"قبلی",next:"بعدی",back_map:"بازگشت",no_content:"محتوایی نیست",ft_copy:"منافع — حقوق محفوظ",ft_langs:"زبان‌ها",
  virtues:["عمره تا عمره کفاره گناهان میان آن دو است","عمره در رمضان برابر حج است","حج و عمره فقر و گناه را می‌زدایند","معتمرین مهمانان خدا هستند"],
  pillars:[{t:"احرام",d:"نیت ورود به نسک"},{t:"طواف",d:"هفت دور حول کعبه"},{t:"سعی",d:"هفت دور بین صفا و مروه"}],
  obligations:[{t:"احرام از میقات",d:"واجب است از میقات تعیین شده"},{t:"تراشیدن یا کوتاه کردن",d:"مردان تراشیدن یا کوتاه کردن، زنان به اندازه سر انگشت"}],
  sunnahs:["کوتاه کردن ناخن قبل از احرام","غسل","عطر زدن به بدن","تلبیه بلند برای مردان","اضطباع","رمل","بوسیدن حجرالاسود","دو رکعت نماز پشت مقام ابراهیم","نوشیدن آب زمزم","تند رفتن بین نشانه‌های سبز","اشتراط"],
  prohibitions:["کوتاه کردن مو یا ناخن","عطر زدن پس از احرام","لباس دوخته برای مردان","پوشاندن سر برای مردان","نقاب و دستکش برای زنان","آمیزش","عقد نکاح","شکار زمینی"],
  miqaat_places:["ذوالحلیفه — میقات مدینه","جحفه — میقات شام","قرن المنازل — میقات نجد","یلملم — میقات یمن","ذات عرق — میقات عراق","اهل مکه: از تنعیم"],
  remember:["عمره یک بار در عمر واجب است","در هر زمانی انجام می‌شود — بهترین در رمضان","احکام را بیاموزید","مدارک را بررسی کنید","آرام باشید","دعا کنید","زن حائض تا پاک نشده طواف نکند"],
},
bn:{bismillah:"আল্লাহর নামে",site_name:"মানাফেয়া",site_desc:"উমরাহ দাওয়াহ",n_home:"হোম",n_vid:"ভিডিও",n_quran:"কুরআন",n_lib:"লাইব্রেরি",n_hajj:"হজ্জ",n_umrah:"উমরাহ",n_contest:"প্রতিযোগিতা",login:"লগইন",hero_title:"উমরাহ: আল্লাহর ঘর পরিদর্শন",hero_desc:"উমরাহ একটি মহান ইবাদত যা বছরের যেকোনো সময় পালন করা যায়",journey_title:"উমরাহর যাত্রা",journey_desc:"ইহরাম থেকে চুল কাটা পর্যন্ত",start_journey:"যাত্রা শুরু",about_title:"উমরাহ সম্পর্কে",virtues_title:"উমরাহর ফযীলত",pillars_title:"উমরাহর রুকন",pillars_desc:"তিনটি রুকন",obligations_title:"উমরাহর ওয়াজিব",obligations_desc:"দুটি ওয়াজিব",sunnahs_title:"উমরাহর সুন্নাহ",miqaat_title:"মীকাত",remember_title:"মনে রাখুন",prohibitions_title:"ইহরামের নিষেধাজ্ঞা",step:"ধাপ",of:"এর মধ্যে",dua:"দোয়া",prev:"আগের",next:"পরের",back_map:"ফিরুন",no_content:"বিষয়বস্তু নেই",ft_copy:"মানাফেয়া — সংরক্ষিত",ft_langs:"ভাষা",
  virtues:["উমরাহ থেকে উমরাহ মধ্যবর্তী গুনাহের কাফফারা","রমজানে উমরাহ হজ্জের সমান","হজ্জ ও উমরাহ দারিদ্র্য ও গুনাহ দূর করে","উমরাহকারীরা আল্লাহর মেহমান"],
  pillars:[{t:"ইহরাম",d:"নুসুকে প্রবেশের নিয়্যত"},{t:"তাওয়াফ",d:"কা'বার চারপাশে সাত পাক"},{t:"সাঈ",d:"সাফা ও মারওয়ার মধ্যে সাত পাক"}],
  obligations:[{t:"মীকাত থেকে ইহরাম",d:"নির্ধারিত মীকাত থেকে ইহরাম বাঁধা"},{t:"চুল কামানো বা ছোট করা",d:"পুরুষ কামায় বা ছোট করে, মহিলা আঙুলের ডগা পরিমাণ কাটে"}],
  sunnahs:["ইহরামের আগে নখ কাটা","গোসল","শরীরে সুগন্ধি","উচ্চস্বরে তালবিয়া","ইদতিবা","রমল","হাজারে আসওয়াদে চুম্বন","মাকামে ইবরাহীমের পেছনে দুই রাকাত","যমযম পান","সবুজ চিহ্নের মধ্যে দ্রুত হাঁটা","ইশতিরাত"],
  prohibitions:["চুল কাটা বা নখ কাটা","সুগন্ধি ব্যবহার","সেলাইকৃত পোশাক (পুরুষ)","মাথা ঢাকা (পুরুষ)","নেকাব ও দস্তানা (মহিলা)","সহবাস","বিবাহ চুক্তি","স্থলপ্রাণী শিকার"],
  miqaat_places:["যুলহুলাইফা — মদীনা","জুহফা — সিরিয়া","কারনুল মানাযিল — নজদ","ইয়ালামলাম — ইয়ামান","যাতু ইরক — ইরাক","মক্কাবাসী: তান'ঈম থেকে"],
  remember:["উমরাহ জীবনে একবার ওয়াজিব","যেকোনো সময় করা যায় — রমজানে সর্বোত্তম","বিধান শিখুন","নথিপত্র যাচাই করুন","শান্ত থাকুন","বেশি বেশি দোয়া করুন","হায়েয অবস্থায় তাওয়াফ করবে না"],
},
hi:{bismillah:"अल्लाह के नाम से",site_name:"मनाफ़ेआ",site_desc:"उमरा दावत",n_home:"होम",n_vid:"वीडियो",n_quran:"कुरान",n_lib:"पुस्तकालय",n_hajj:"हज",n_umrah:"उमरा",n_contest:"प्रतियोगिता",login:"लॉगिन",hero_title:"उमरा: अल्लाह के घर की ज़ियारत",hero_desc:"उमरा एक महान इबादत है जो साल के किसी भी वक़्त अदा की जा सकती है",journey_title:"उमरे का सफ़र",journey_desc:"इहराम से सिर मुंडाने तक",start_journey:"शुरू करें",about_title:"उमरा के बारे में",virtues_title:"उमरा की फ़ज़ीलत",pillars_title:"उमरा के अरकान",pillars_desc:"तीन रुकन",obligations_title:"उमरा के वाजिबात",obligations_desc:"दो वाजिब",sunnahs_title:"उमरा की सुन्नतें",miqaat_title:"मीक़ात",remember_title:"याद रखें",prohibitions_title:"इहराम की मनाही",step:"चरण",of:"में से",dua:"दुआ",prev:"पिछला",next:"अगला",back_map:"वापस",no_content:"सामग्री नहीं",ft_copy:"मनाफ़ेआ — अधिकार सुरक्षित",ft_langs:"भाषाएं",
  virtues:["उमरा से उमरा बीच के गुनाहों का कफ़्फ़ारा","रमज़ान में उमरा हज के बराबर","हज और उमरा ग़रीबी और गुनाह दूर करते हैं","उमरा करने वाले अल्लाह के मेहमान हैं"],
  pillars:[{t:"इहराम",d:"नुसुक में दाख़िल होने की नीयत"},{t:"तवाफ़",d:"काबा के सात चक्कर"},{t:"सई",d:"सफ़ा और मरवा के बीच सात चक्कर"}],
  obligations:[{t:"मीक़ात से इहराम",d:"तय मीक़ात से इहराम बांधना"},{t:"सिर मुंडाना या बाल छोटे करना",d:"मर्द मुंडाए या छोटे करे, औरत उंगली के पोर भर काटे"}],
  sunnahs:["इहराम से पहले नाख़ून काटना","ग़ुस्ल","ख़ुशबू लगाना","ऊंची आवाज़ में तल्बिया","इज़्तिबाअ","रमल","हजर-ए-असवद को चूमना","मक़ाम-ए-इब्राहीम के पीछे दो रकअत","ज़मज़म पीना","हरी निशानियों के बीच तेज़ चलना","इशतिरात"],
  prohibitions:["बाल काटना या नाख़ून तराशना","ख़ुशबू लगाना","सिला हुआ कपड़ा (मर्द)","सिर ढांकना (मर्द)","नक़ाब और दस्ताने (औरत)","जिमाअ","निकाह","ज़मीनी शिकार"],
  miqaat_places:["ज़ुलहुलैफ़ा — मदीना","जुहफ़ा — शाम","क़रनुल मनाज़िल — नज्द","यलमलम — यमन","ज़ात इर्क़ — इराक़","मक्का वाले: तन'ईम से"],
  remember:["उमरा ज़िंदगी में एक बार वाजिब","किसी भी वक़्त — रमज़ान में सबसे अफ़ज़ल","अहकाम सीखें","दस्तावेज़ चेक करें","शांत रहें","ख़ूब दुआ करें","हाइज़ा औरत पाक होने तक तवाफ़ नहीं करे"],
},
};

// ─── 5 Umrah Journey Steps (ar/en) ───
const ST={
ar:[
  {id:1,t:"الإحرام من الميقات",s:"🕋",d:"عند الوصول إلى الميقات يغتسل المعتمر ويتطيب في بدنه ويلبس ملابس الإحرام (إزار ورداء أبيضين للرجل). ينوي العمرة بقلبه ويتلفظ: لبيك اللهم عمرة. ثم يلبي بالتلبية المعروفة ويكثر منها حتى يبدأ الطواف. يُستحب الاشتراط لمن يخاف ألا يتم نسكه.",du:"لبيك اللهم لبيك، لبيك لا شريك لك لبيك، إن الحمد والنعمة لك والملك، لا شريك لك"},
  {id:2,t:"الطواف بالكعبة",s:"🔄",d:"يدخل المسجد الحرام بالرجل اليمنى ويقول دعاء دخول المسجد. يتجه إلى الكعبة ويبدأ الطواف من الحجر الأسود سبعة أشواط كاملة، يجعل البيت عن يساره. يُستحب الاضطباع (كشف الكتف الأيمن) والرمل (المشي بخطوات سريعة) في الأشواط الثلاثة الأولى. يقول بين الركنين: ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار. بعد الطواف يصلي ركعتين خلف مقام إبراهيم.",du:"ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار"},
  {id:3,t:"الصلاة عند المقام",s:"🤲",d:"بعد إتمام الطواف يتجه إلى مقام إبراهيم ويصلي خلفه ركعتين. يقرأ في الأولى سورة الكافرون وفي الثانية سورة الإخلاص. ثم يشرب من ماء زمزم ويدعو الله بما يشاء.",du:"اللهم اجعلني من التوابين واجعلني من المتطهرين"},
  {id:4,t:"السعي بين الصفا والمروة",s:"🚶",d:"يتوجه إلى الصفا ويبدأ السعي. يسعى سبعة أشواط: من الصفا إلى المروة شوط، ومن المروة إلى الصفا شوط. يدعو على كل من الصفا والمروة ويرفع يديه. يُستحب الإسراع بين العلامتين الخضراوين للرجال. يقول على الصفا والمروة: إن الصفا والمروة من شعائر الله.",du:"لا إله إلا الله وحده لا شريك له، له الملك وله الحمد يحيي ويميت وهو على كل شيء قدير"},
  {id:5,t:"الحلق أو التقصير",s:"✂️",d:"بعد إتمام السعي يحلق الرجل رأسه بالكامل أو يقصر شعره (الحلق أفضل). المرأة تقصر من أطراف شعرها قدر أنملة (طرف الإصبع). بهذا تتم العمرة ويتحلل المعتمر من إحرامه — فيحل له كل ما كان محرماً عليه.",du:"الحمد لله الذي قضى عنا نسكنا، اللهم اجعلها عمرة مبرورة وذنباً مغفوراً"},
],
en:[
  {id:1,t:"Ihram at the Miqat",s:"🕋",d:"Upon reaching the Miqat, the pilgrim bathes, applies fragrance to the body, and wears Ihram garments (two white unstitched cloths for men). He intends Umrah in his heart and declares: Labbayk Allahumma Umrah. Then recites the Talbiyah frequently until beginning Tawaf. It is recommended to make the conditional statement for those who fear they may not complete their rites.",du:"Labbayk Allahumma labbayk, labbayk la shareeka laka labbayk, innal-hamda wan-ni'mata laka wal-mulk, la shareeka lak"},
  {id:2,t:"Tawaf around the Ka'bah",s:"🔄",d:"Enter Al-Masjid Al-Haram with the right foot and recite the entry supplication. Proceed to the Ka'bah and begin Tawaf from the Black Stone — seven complete circuits keeping the Ka'bah to your left. Idtiba (uncovering right shoulder) and Raml (brisk walking) are recommended in the first three circuits. Between the Yemeni Corner and the Black Stone say: Our Lord, give us good in this world and the Hereafter. After Tawaf, pray two rak'ahs behind Maqam Ibrahim.",du:"Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire"},
  {id:3,t:"Prayer at Maqam Ibrahim",s:"🤲",d:"After completing Tawaf, proceed to Maqam Ibrahim and pray two rak'ahs behind it. Recite Surah Al-Kafirun in the first and Surah Al-Ikhlas in the second. Then drink Zamzam water and supplicate to Allah with whatever you wish.",du:"O Allah, make me among those who repent and among those who purify themselves"},
  {id:4,t:"Sa'i between Safa and Marwah",s:"🚶",d:"Proceed to Safa and begin Sa'i. Walk seven circuits: Safa to Marwah is one circuit, Marwah to Safa is another. Supplicate at each hill with raised hands. Men should walk briskly between the green markers. At Safa and Marwah recite: Indeed Safa and Marwah are among the symbols of Allah.",du:"None has the right to be worshipped except Allah alone, with no partner. To Him belongs all sovereignty and praise. He gives life and causes death, and He is over all things omnipotent"},
  {id:5,t:"Shaving or Trimming",s:"✂️",d:"After completing Sa'i, men shave their heads completely or trim their hair (shaving is preferred). Women trim a fingertip's length from their hair. With this, the Umrah is complete and the pilgrim exits the state of Ihram — everything that was prohibited becomes permissible again.",du:"Praise be to Allah who fulfilled our rite. O Allah, make it an accepted Umrah and forgiven sins"},
],
};

const IP=()=><svg className="absolute inset-0 w-full h-full opacity-[0.03]" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="igu" x="0" y="0" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M40 0L80 40L40 80L0 40Z" fill="none" stroke="currentColor" strokeWidth="0.5"/><circle cx="40" cy="40" r="15" fill="none" stroke="currentColor" strokeWidth="0.5"/></pattern></defs><rect width="100%" height="100%" fill="url(#igu)"/></svg>;
const Sec=({title,children,id})=><section id={id} className="py-14 sm:py-20 max-w-5xl mx-auto px-4 sm:px-6"><div className="flex items-center justify-center gap-4 mb-10"><div className="h-px flex-1 max-w-24" style={{background:'#C8A951'}}></div><h2 className="text-2xl sm:text-3xl font-black text-center" style={{fontFamily:'Amiri,serif',color:'#1B3A4B'}}>{title}</h2><div className="h-px flex-1 max-w-24" style={{background:'#C8A951'}}></div></div>{children}</section>;
const Div=()=><div className="max-w-xs mx-auto" style={{height:'1px',background:'linear-gradient(90deg,transparent,#C8A951,transparent)'}}></div>;

// Circle Map
const CircleMap=({stations,onSelect,t})=>{
  const n=stations.length;const R=34;
  return(<div className="relative mx-auto" style={{width:'min(420px,85vw)',height:'min(420px,85vw)'}}>
    <svg viewBox="0 0 100 100" className="w-full h-full">
      <circle cx="50" cy="50" r={R} fill="none" stroke="rgba(200,169,81,0.25)" strokeWidth="0.5" strokeDasharray="2 1"/>
      {stations.map((s,i)=>{const a=(i/n)*2*Math.PI-Math.PI/2;const cx=50+R*Math.cos(a);const cy=50+R*Math.sin(a);const lx=50+(R+9)*Math.cos(a);const ly=50+(R+9)*Math.sin(a);const isR=lx>50;
        return <g key={i} style={{cursor:'pointer'}} onClick={()=>onSelect(i)}><circle cx={cx} cy={cy} r="4.5" fill="#E5E7EB" stroke="white" strokeWidth="0.8"/><text x={cx} y={cy+0.5} textAnchor="middle" dominantBaseline="middle" fontSize="3" fill="#1B3A4B">{s.s}</text><text x={lx} y={ly} textAnchor={isR?"start":"end"} dominantBaseline="middle" fontSize="2" fill="#6B7280" fontWeight="600" fontFamily="Tajawal">{s.t.length>16?s.t.slice(0,16)+'…':s.t}</text></g>})}
    </svg>
    <div className="absolute rounded-full flex flex-col items-center justify-center" style={{top:'50%',left:'50%',transform:'translate(-50%,-50%)',width:'42%',height:'42%',background:'#1B3A4B',boxShadow:'0 0 40px rgba(27,58,75,0.3)'}}>
      <span className="text-2xl sm:text-3xl block mb-1">🕌</span>
      <h3 className="text-xs sm:text-sm font-black text-white text-center px-2" style={{fontFamily:'Amiri,serif'}}>{t("journey_title")}</h3>
      <button onClick={()=>onSelect(0)} className="mt-2 px-3 py-1.5 rounded-lg text-white font-bold transition-all hover:scale-105" style={{background:'#C8A951',fontSize:'9px'}}>{t("start_journey")}</button>
    </div>
  </div>);
};

// Step Detail
const StepView=({stations,cur,setCur,t,dir,onBack})=>{
  const s=stations[cur];const total=stations.length;const prog=((cur+1)/total)*100;
  const go=(i)=>{setCur(i);window.scrollTo({top:0,behavior:'smooth'})};
  return(<div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
    <button onClick={onBack} className="flex items-center gap-2 mb-6 text-sm font-medium px-4 py-2 rounded-xl hover:bg-gray-100" style={{color:'#1B3A4B'}}><span>{dir==="rtl"?"→":"←"}</span>{t("back_map")}</button>
    <div className="mb-6"><div className="flex justify-between text-xs mb-1.5" style={{color:'#6B7280'}}><span>{t("step")} {cur+1} {t("of")} {total}</span><span>{Math.round(prog)}%</span></div><div className="w-full h-2 rounded-full bg-gray-100"><div className="h-full rounded-full transition-all duration-500" style={{width:`${prog}%`,background:'linear-gradient(90deg,#9E832E,#C8A951)'}}></div></div></div>
    <div className="flex gap-2 justify-center mb-6">{stations.map((_,i)=><button key={i} onClick={()=>go(i)} className="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold transition-all" style={{background:i===cur?'#C8A951':i<cur?'#1B3A4B':'#E5E7EB',color:i<=cur?'white':'#6B7280',transform:i===cur?'scale(1.15)':'scale(1)'}}>{i+1}</button>)}</div>
    <div key={cur} style={{animation:'fu .5s ease-out'}}>
      <div className="rounded-3xl overflow-hidden shadow-xl mb-6" style={{border:'1px solid rgba(200,169,81,0.2)'}}><div className="p-8 sm:p-12 text-center relative" style={{background:'linear-gradient(135deg,#0F2530,#1B3A4B)'}}><IP/><div className="relative z-10"><span className="text-5xl block mb-3">{s.s}</span><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-3" style={{background:'rgba(200,169,81,0.15)',border:'1px solid rgba(200,169,81,0.3)'}}><span className="text-xs font-bold" style={{color:'#C8A951'}}>{t("step")} {cur+1} {t("of")} {total}</span></div><h2 className="text-2xl sm:text-4xl font-black text-white" style={{fontFamily:'Amiri,serif'}}>{s.t}</h2></div></div></div>
      <div className="bg-white rounded-3xl shadow-lg p-6 sm:p-10 mb-6" style={{border:'1px solid rgba(200,169,81,0.1)'}}><p className="text-base sm:text-lg leading-[2]" style={{fontFamily:'Amiri,serif',color:'#1a1a2e'}}>{s.d}</p></div>
      {s.du&&<div className="rounded-3xl p-6 sm:p-8 mb-8" style={{background:'rgba(200,169,81,0.06)',border:'1px solid rgba(200,169,81,0.2)'}}><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:'rgba(200,169,81,0.15)'}}><span>🤲</span></div><h3 className="text-sm font-bold" style={{color:'#9E832E'}}>{t("dua")}</h3></div><p className="text-lg sm:text-xl leading-[2] text-center" style={{fontFamily:'Amiri,serif',color:'#1B3A4B',direction:'rtl'}}>{s.du}</p></div>}
      <div className="flex gap-3"><button disabled={cur===0} onClick={()=>go(cur-1)} className="flex-1 py-4 rounded-xl font-bold text-sm" style={{background:cur===0?'#E5E7EB':'#1B3A4B',color:cur===0?'#9CA3AF':'white',opacity:cur===0?.5:1}}>{dir==="rtl"?"→":"←"} {t("prev")}</button><button disabled={cur===total-1} onClick={()=>go(cur+1)} className="flex-1 py-4 rounded-xl font-bold text-sm text-white" style={{background:'linear-gradient(135deg,#9E832E,#C8A951)'}}>{cur===total-1?"✓":t("next")} {cur<total-1?(dir==="rtl"?"←":"→"):""}</button></div>
    </div>
  </div>);
};

export default function ManafaaUmrahPage(){
  const[lang,setLang]=useState("ar");const[showLM,setShowLM]=useState(false);const[scrolled,setScrolled]=useState(false);const[mob,setMob]=useState(false);const[activeStep,setActiveStep]=useState(null);
  const lo=L.find(l=>l.c===lang)||L[0];const dir=lo.d;const ui=T[lang]||T.ar;const t=k=>ui[k]||T.ar[k]||k;
  const stations=ST[lang]||null;const has=stations&&stations.length>0;
  useEffect(()=>{const h=()=>setScrolled(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);
  useEffect(()=>{setActiveStep(null)},[lang]);
  const nav=[{k:"n_home"},{k:"n_vid"},{k:"n_quran"},{k:"n_lib"},{k:"n_hajj"},{k:"n_umrah"},{k:"n_contest"}];

  return(<div dir={dir} className="min-h-screen bg-[#FAFBFC]" style={{fontFamily:"'Tajawal','Segoe UI',sans-serif"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700;800;900&family=Amiri:wght@400;700&display=swap');*{box-sizing:border-box;margin:0;padding:0}@keyframes fu{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes sd{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}@keyframes sh{0%{background-position:-200% 0}100%{background-position:200% 0}}.afu{animation:fu .8s ease-out forwards}.gn{background:rgba(27,58,75,.95);backdrop-filter:blur(20px)}.hg{background:linear-gradient(135deg,#0F2530 0%,#1B3A4B 30%,#2C5F7C 70%,#1B3A4B 100%)}.gs{background:linear-gradient(90deg,#9E832E,#C8A951,#E8D48B,#C8A951,#9E832E);background-size:200% 100%;animation:sh 4s linear infinite;-webkit-background-clip:text;-webkit-text-fill-color:transparent}.ni{position:relative;transition:all .3s}.ni::after{content:'';position:absolute;bottom:-4px;${dir==="rtl"?"right":"left"}:0;width:0;height:2px;background:#C8A951;transition:width .3s}.ni:hover::after{width:100%}.ch{transition:all .4s cubic-bezier(.4,0,.2,1)}.ch:hover{transform:translateY(-6px);box-shadow:0 20px 40px -12px rgba(27,58,75,.12)}`}</style>

    <div className="w-full py-2 text-center text-sm" style={{background:'#0F2530',color:'#C8A951'}}>{t("bismillah")}</div>

    <nav className={`gn sticky top-0 z-50 transition-all duration-500 ${scrolled?'shadow-2xl':''}`}><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="flex items-center justify-between h-16 sm:h-20">
      <div className="flex items-center gap-3"><div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full flex items-center justify-center" style={{background:'#C8A951',color:'#0F2530'}}><span className="text-lg sm:text-xl font-bold" style={{fontFamily:'Amiri,serif'}}>م</span></div><div className="hidden sm:block"><h1 className="text-white font-bold text-base">{t("site_name")}</h1><p className="text-xs" style={{color:'#C8A951'}}>{t("site_desc")}</p></div></div>
      <div className="hidden lg:flex items-center gap-1">{nav.map((n,i)=><Link key={i} to={n.href} className={`ni text-sm px-3 py-2 rounded-lg ${n.k==="n_umrah"?"text-white bg-white/10":"text-white/70 hover:text-white hover:bg-white/5"}`}>{t(n.k)}</Link>)}</div>
      <div className="flex items-center gap-2 sm:gap-3">
        <div className="relative"><button onClick={()=>setShowLM(!showLM)} className="flex items-center gap-1.5 text-white/80 hover:text-white text-sm px-2.5 py-1.5 rounded-lg hover:bg-white/5"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9"/></svg><span className="hidden sm:inline">{lo.n}</span></button>
          {showLM&&<div className={`absolute ${dir==="rtl"?"left-0":"right-0"} top-full mt-2 w-44 bg-white rounded-xl shadow-2xl border border-gray-100 overflow-hidden z-50`} style={{animation:'sd .3s ease-out'}}>{L.map(l=><button key={l.c} onClick={()=>{setLang(l.c);setShowLM(false)}} className={`w-full px-4 py-2.5 text-sm hover:bg-gray-50 flex items-center justify-between ${lang===l.c?'bg-blue-50 font-bold':''}`} style={{textAlign:l.d==="rtl"?"right":"left",color:lang===l.c?'#1B3A4B':'#1a1a2e'}}><span>{l.n}</span>{lang===l.c&&<span style={{color:'#C8A951'}}>✓</span>}</button>)}</div>}
        </div>
        <button onClick={()=>setMob(!mob)} className="lg:hidden text-white p-2 rounded-lg hover:bg-white/10"><svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">{mob?<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12"/>:<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16"/>}</svg></button>
      </div>
    </div>
    {mob&&<div className="lg:hidden pb-4" style={{animation:'sd .3s ease-out'}}><div className="bg-white/5 rounded-xl p-2">{nav.map((n,i)=><Link key={i} to={n.href} onClick={()=>setMob(false)} className={`flex items-center gap-3 px-4 py-3 rounded-lg ${n.k==="n_umrah"?"text-white bg-white/10":"text-white/80 hover:bg-white/5"}`}>{t(n.k)}</Link>)}</div></div>}
    </div></nav>

    {activeStep!==null&&has?<StepView stations={stations} cur={activeStep} setCur={setActiveStep} t={t} dir={dir} onBack={()=>{setActiveStep(null);window.scrollTo({top:0,behavior:'smooth'})}}/>:(
    <>
      <section className="hg relative overflow-hidden py-16 sm:py-24"><IP/><div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 text-center afu">
        <span className="text-5xl sm:text-6xl block mb-4">🕌</span>
        <h1 className="text-3xl sm:text-5xl lg:text-6xl font-black gs mb-4" style={{fontFamily:'Amiri,serif'}}>{t("hero_title")}</h1>
        <p className="text-sm sm:text-base text-white/60 max-w-2xl mx-auto">{t("hero_desc")}</p>
      </div></section>

      <Sec title={t("virtues_title")} id="virtues"><div className="grid grid-cols-1 sm:grid-cols-2 gap-5">{(ui.virtues||[]).map((v,i)=><div key={i} className="ch bg-white rounded-2xl shadow-md p-6 flex gap-4" style={{border:'1px solid rgba(200,169,81,0.1)'}}><div className="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0" style={{background:'rgba(200,169,81,0.1)'}}><span style={{color:'#9E832E',fontWeight:'bold'}}>✓</span></div><p className="text-sm leading-relaxed" style={{color:'#1a1a2e'}}>{v}</p></div>)}</div></Sec>
      <Div/>

      <Sec title={t("pillars_title")} id="pillars"><p className="text-center text-sm mb-8" style={{color:'#6B7280'}}>{t("pillars_desc")}</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-5">{(ui.pillars||[]).map((p,i)=><div key={i} className="ch bg-white rounded-2xl shadow-md overflow-hidden" style={{border:'1px solid rgba(200,169,81,0.1)'}}><div className="p-4 text-center" style={{background:'linear-gradient(135deg,#0F2530,#1B3A4B)'}}><span className="text-white font-black text-lg" style={{fontFamily:'Amiri,serif'}}>{p.t}</span></div><div className="p-5"><p className="text-sm leading-relaxed" style={{color:'#1a1a2e'}}>{p.d}</p></div></div>)}</div></Sec>
      <Div/>

      <Sec title={t("obligations_title")} id="obligations"><p className="text-center text-sm mb-8" style={{color:'#6B7280'}}>{t("obligations_desc")}</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-5">{(ui.obligations||[]).map((o,i)=><div key={i} className="ch bg-white rounded-2xl shadow-md p-6" style={{border:'1px solid rgba(200,169,81,0.1)'}}><div className="w-10 h-10 rounded-xl flex items-center justify-center mb-3" style={{background:'rgba(239,68,68,0.08)'}}><span className="text-sm font-black" style={{color:'#dc2626'}}>{i+1}</span></div><h4 className="font-bold text-sm mb-2" style={{color:'#1B3A4B'}}>{o.t}</h4><p className="text-xs leading-relaxed" style={{color:'#6B7280'}}>{o.d}</p></div>)}</div></Sec>
      <Div/>

      <Sec title={t("sunnahs_title")} id="sunnahs"><div className="bg-white rounded-3xl shadow-lg p-6 sm:p-10" style={{border:'1px solid rgba(200,169,81,0.1)'}}><div className="space-y-4">{(ui.sunnahs||[]).map((s,i)=><div key={i} className="flex items-start gap-3"><div className="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5" style={{background:'#1B3A4B'}}><span className="text-white text-xs font-bold">{i+1}</span></div><p className="text-sm leading-relaxed" style={{color:'#1a1a2e'}}>{s}</p></div>)}</div></div></Sec>
      <Div/>

      <Sec title={t("prohibitions_title")} id="prohibitions"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{(ui.prohibitions||[]).map((p,i)=><div key={i} className="flex items-center gap-3 bg-white rounded-xl shadow-sm p-4" style={{border:'1px solid rgba(239,68,68,0.08)'}}><span className="text-lg">🚫</span><p className="text-sm" style={{color:'#1a1a2e'}}>{p}</p></div>)}</div></Sec>
      <Div/>

      {has&&<Sec title={t("journey_title")} id="journey"><p className="text-center text-sm mb-8" style={{color:'#6B7280'}}>{t("journey_desc")}</p><CircleMap stations={stations} onSelect={(i)=>{setActiveStep(i);window.scrollTo({top:0,behavior:'smooth'})}} t={t}/><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 mt-12">{stations.map((s,i)=><button key={i} onClick={()=>{setActiveStep(i);window.scrollTo({top:0,behavior:'smooth'})}} className="ch bg-white rounded-xl shadow-sm p-4 text-center" style={{border:'1px solid rgba(200,169,81,0.08)'}}><span className="text-2xl block mb-2">{s.s}</span><p className="text-xs font-bold" style={{color:'#1B3A4B'}}>{s.t}</p></button>)}</div></Sec>}
      <Div/>

      <Sec title={t("miqaat_title")} id="miqaat"><div className="bg-white rounded-2xl shadow-md p-6" style={{border:'1px solid rgba(200,169,81,0.1)'}}><div className="space-y-3">{(ui.miqaat_places||[]).map((p,i)=><div key={i} className="flex items-center gap-3"><div className="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0" style={{background:'#1B3A4B'}}><span className="text-white text-xs font-bold">{i+1}</span></div><p className="text-sm" style={{color:'#1a1a2e'}}>{p}</p></div>)}</div></div></Sec>
      <Div/>

      <Sec title={t("remember_title")} id="remember"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{(ui.remember||[]).map((r,i)=><div key={i} className="flex items-start gap-3 bg-white rounded-xl shadow-sm p-5" style={{border:'1px solid rgba(200,169,81,0.08)'}}><span className="text-lg">⚠️</span><p className="text-sm leading-relaxed" style={{color:'#1a1a2e'}}>{r}</p></div>)}</div></Sec>
    </>)}

    <footer style={{background:'#0F2530'}}><div className="max-w-7xl mx-auto px-4 sm:px-6 py-16"><div className="grid grid-cols-1 md:grid-cols-2 gap-10"><div><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-full flex items-center justify-center" style={{background:'#C8A951',color:'#0F2530'}}><span className="font-bold" style={{fontFamily:'Amiri,serif'}}>م</span></div><div><h3 className="text-white font-bold">{t("site_name")}</h3><p className="text-xs" style={{color:'#C8A951'}}>{t("site_desc")}</p></div></div></div><div><h4 className="text-white font-bold mb-4">{t("ft_langs")}</h4><div className="flex flex-wrap gap-2">{L.map(l=><button key={l.c} onClick={()=>setLang(l.c)} className="text-xs px-3 py-1.5 rounded-full transition-all" style={{background:lang===l.c?'#C8A951':'rgba(255,255,255,.05)',color:lang===l.c?'#0F2530':'rgba(255,255,255,.6)',fontWeight:lang===l.c?'bold':'normal'}}>{l.n}</button>)}</div></div></div><div className="mt-12 pt-8 text-center" style={{borderTop:'1px solid rgba(255,255,255,.05)'}}><p className="text-white/30 text-sm">© {new Date().getFullYear()} {t("ft_copy")}</p></div></div></footer>

    {(showLM||mob)&&<div className="fixed inset-0 z-40" onClick={()=>{setShowLM(false);setMob(false)}}/>}
  </div>);
}
